---@class AccelerationEvent @Structure describing acceleration status of the device.
---@field deltaTime fun() @Amount of time passed since last accelerometer measurement.
---@field acceleration fun() @Value of acceleration.
