---@class AI.NavMeshEditorHelpers @NavMesh utility functionality effective only in the Editor.
---@field DrawBuildDebug fun() @Displays in the Editor the precise intermediate data used during the build process of the specified NavMesh.
