---@class Analytics.AnalyticsSessionState @Session tracking states.
---@field kSessionStarted fun() @Session tracking has started.
---@field kSessionPaused fun() @Session tracking has paused.
---@field kSessionStopped fun() @Session tracking has stopped.
---@field kSessionResumed fun() @Session tracking has resumed.
