---@class Android.AndroidAssetPackInfo @Represents the download progress of a single Android asset pack.
---@field size fun() @The total size of the Android asset pack in bytes.
---@field error fun() @Indicates an error which the device encountered when downloading the Android asset pack.
---@field transferProgress fun() @The transfering progress of the downloaded Android asset pack.
---@field bytesDownloaded fun() @The downloaded size of the Android asset pack in bytes.
---@field status fun() @The status of the Android asset pack that the device is downloading.
---@field name fun() @The name of the Android asset pack that the device is downloading.
