---@class Animations.ConstraintSource @Represents a source for the constraint.
---@field weight fun() @The weight of the source in the evaluation of the constraint.
---@field sourceTransform fun() @The transform component of the source object.
