---@class AnimatorControllerParameterType @The type of the parameter.
---@field Bool fun() @Boolean type parameter.
---@field Int fun() @Int type parameter.
---@field Float fun() @Float type parameter.
---@field Trigger fun() @Trigger type parameter.
