---@class Animations.PropertySceneHandle @Handle to read a Component property on an object in the Scene.
---@field Resolve fun() @Resolves the handle.
---@field GetInt fun() @Gets the integer property value from an object in the Scene.
---@field SetFloat fun() @Sets the float property value to an object in the Scene.
---@field IsResolved fun() @Returns whether or not the handle is resolved.
---@field IsValid fun() @Returns whether or not the handle is valid.
---@field GetBool fun() @Gets the boolean property value from an object in the Scene.
---@field SetBool fun() @Sets the boolean property value to an object in the Scene.
---@field SetInt fun() @Sets the integer property value to an object in the Scene.
---@field GetFloat fun() @Gets the float property value from an object in the Scene.
