---@class Animations.PropertyStreamHandle @Handle for a Component property on an object in the AnimationStream.
---@field Resolve fun() @Resolves the handle.
---@field GetFloat fun() @Gets the float property value from a stream.
---@field SetFloat fun() @Sets the float property value into a stream.
---@field IsResolved fun() @Returns whether or not the handle is resolved.
---@field IsValid fun() @Returns whether or not the handle is valid.
---@field SetInt fun() @Sets the integer property value into a stream.
---@field GetBool fun() @Gets the boolean property value from a stream.
---@field SetBool fun() @Sets the boolean property value into a stream.
---@field GetReadMask fun() @Gets the read mask of the property.
---@field GetInt fun() @Gets the integer property value from a stream.
