---@class Animations.AnimatorConditionMode @The mode of the condition.
---@field If fun() @The condition is true when the parameter value is true.
---@field NotEqual fun() @The condition is true when the parameter value is not equal to the threshold.
---@field Greater fun() @The condition is true when parameter value is greater than the threshold.
---@field Less fun() @The condition is true when the parameter value is less than the threshold.
---@field IfNot fun() @The condition is true when the parameter value is false.
---@field Equals fun() @The condition is true when parameter value is equal to the threshold.
