---@class Animations.AnimationSceneHandleUtility @Static class providing utility functions for animation scene handles.
---@field ReadFloats fun() @Reads float properties from the PropertySceneHandle array (handles) and stores the floats in the provided buffer. The buffer must have enough allocated space to store all values.
---@field ReadInts fun() @Reads integer properties from the PropertySceneHandle array (handles) and stores the integers in the provided buffer. The buffer must have enough allocated space to store all values.
