---@class Animations.AnimationClipPlayable @A Playable that controls an AnimationClip.
---@field Create fun() @Creates an AnimationClipPlayable in the PlayableGraph.
---@field GetAnimationClip fun() @Returns the AnimationClip stored in the AnimationClipPlayable.
---@field SetApplyPlayableIK fun() @Requests OnAnimatorIK to be called on the animated GameObject.
---@field SetApplyFootIK fun() @Sets the value of the ApplyFootIK flag.
---@field GetApplyFootIK fun() @Returns the state of the ApplyFootIK flag.
---@field GetApplyPlayableIK fun() @Returns the state of the ApplyPlayableIK flag.
