---@class AnimationInfo @Information about what animation clips is played and its weight.
---@field clip fun() @Animation clip that is played.
---@field weight fun() @The weight of the animation clip.
