---@class AnimatorClipInfo @Information about clip being played and blended by the Animator.
---@field clip fun() @Returns the animation clip played by the Animator.
---@field weight fun() @Returns the blending weight used by the Animator to blend this clip.
