---@class AnimatedValues.AnimBool @Lerp from 0 - 1.
---@field GetValue fun() @Type specific implementation of BaseAnimValue_1.GetValue.
---@field faded fun() @Retuns the float value of the tween.
---@field ctor fun() @Constructor.
---@field Fade fun() @Returns a value between from and to depending on the current value of the bools animation.
