---@class AnisotropicFiltering @Anisotropic filtering mode.
---@field ForceEnable fun() @Enable anisotropic filtering for all textures.
---@field Disable fun() @Disable anisotropic filtering for all textures.
---@field Enable fun() @Enable anisotropic filtering, as set for each texture.
