---@class Assertions @nil
---@field Must fun() @nil
---@field Comparers fun() @nil
---@field AssertionException fun() @An exception that is thrown when an assertion fails.
---@field Assert Assertions.Assert @The Assert class contains assertion methods for setting invariants in the code.
