---@class AssetImporter.SourceAssetIdentifier @Represents a unique identifier for a sub-asset embedded in an imported Asset (such as an FBX file).
---@field name fun() @The name of the Asset.
---@field ctor fun() @Constructs a SourceAssetIdentifier.
---@field type fun() @The type of the Asset.
