---@class AudioType @Type of the imported(native) data.
---@field MPEG fun() @MP2/MP3 MPEG.
---@field OGGVORBIS fun() @Ogg vorbis.
---@field XMA fun() @Xbox360 XMA.
---@field AUDIOQUEUE fun() @iPhone hardware decoder, supports AAC, ALAC and MP3. Extracodecdata is a pointer to an FMOD_AUDIOQUEUE_EXTRACODECDATA structure.
---@field AIFF fun() @Aiff.
---@field VAG fun() @VAG.
---@field ACC fun() @Acc - not supported.
---@field XM fun() @FastTracker 2 XM.
---@field WAV fun() @Microsoft WAV.
---@field UNKNOWN fun() @3rd party / unknown plugin format.
---@field S3M fun() @ScreamTracker 3.
---@field IT fun() @Impulse tracker.
---@field MOD fun() @Protracker / Fasttracker MOD.
