---@class Audio.AudioMixerUpdateMode @The mode in which an AudioMixer should update its time.
---@field Normal fun() @Update the AudioMixer with scaled game time.
---@field UnscaledTime fun() @Update the AudioMixer with unscaled realtime.
