---@class AudioCompressionFormat @An enum containing different compression types.
---@field Vorbis fun() @Vorbis compression format.
---@field ATRAC9 fun() @Sony proprietary hardware format.
---@field MP3 fun() @MPEG Audio Layer III.
---@field HEVAG fun() @Sony proprietory hardware codec.
---@field VAG fun() @Sony proprietary hardware format.
---@field PCM fun() @Uncompressed pulse-code modulation.
---@field GCADPCM fun() @Nintendo ADPCM audio compression format.
---@field ADPCM fun() @Adaptive differential pulse-code modulation.
---@field XMA fun() @Xbox One proprietary hardware format.
---@field AAC fun() @AAC Audio Compression.
