---@class AudioSampleRateSetting @The sample rate setting used within the AudioImporter. This defines the sample rate conversion of audio on import.
---@field PreserveSampleRate fun() @Do not change the sample rate of the imported audio file. The sample rate will be preserved for the imported AudioClip.
---@field OverrideSampleRate fun() @Override the sample rate of the imported audio file with a custom value.
---@field OptimizeSampleRate fun() @Let Unity deduce the optimal sample rate for the AudioClip being imported. The audio file will be analysed and a minimal sample rate chosen while still preserving audio quality.
