---@class AvatarIKHint @IK Hint.
---@field RightKnee fun() @The right knee IK hint.
---@field LeftElbow fun() @The left elbow IK hint.
---@field LeftKnee fun() @The left knee IK hint.
---@field RightElbow fun() @The right elbow IK hint.
