---@class BitStream @The BitStream class represents seralized variables, packed into a stream.
---@field Serialize fun() @Serializes different types of variables.
---@field isWriting fun() @Is the BitStream currently being written? (Read Only)
---@field isReading fun() @Is the BitStream currently being read? (Read Only)
