---@class BoneWeight @Describes 4 skinning bone weights that affect a vertex in a mesh.
---@field boneIndex3 fun() @Index of fourth bone.
---@field weight3 fun() @Skinning weight for fourth bone.
---@field weight2 fun() @Skinning weight for third bone.
---@field weight1 fun() @Skinning weight for second bone.
---@field boneIndex2 fun() @Index of third bone.
---@field boneIndex0 fun() @Index of first bone.
---@field boneIndex1 fun() @Index of second bone.
---@field weight0 fun() @Skinning weight for first bone.
