---@class BoxCollider2D @Collider for 2D physics representing an axis-aligned rectangle.
---@field autoTiling fun() @Determines whether the BoxCollider2D's shape is automatically updated based on a SpriteRenderer's tiling properties.
---@field center fun() @The center point of the collider in local space.
---@field edgeRadius fun() @Controls the radius of all edges created by the collider.
---@field size fun() @The width and height of the rectangle.
