---@class Build.IPreprocessShaders @Implement this interface to receive a callback before a shader is compiled.
---@field OnProcessShader fun() @Implement this interface to receive a callback before a shader snippet is compiled.
