---@class Build.Content.ContentBuildFlags @Build options for content.
---@field None fun() @Build content with no additional options.
---@field StripUnityVersion fun() @Build Flag to indicate the Unity Version should not be written to the serialized file.
---@field DisableWriteTypeTree fun() @Do not include type information within the built content.
---@field DevelopmentBuild fun() @Build a development version of the content files.
