---@class Build.Content.SceneLoadInfo @Container for holding preload information for a given serialized Scene in an AssetBundle.
---@field asset fun() @GUID for the given Scene.
---@field ctor fun() @Default constructor for an empty SceneLoadInfo.
---@field address fun() @Friendly name used to load the built Scene from an asset bundle.
---@field internalName fun() @Internal name used to load the built Scene from an asset bundle.
