---@class Build.Reporting.ScenesUsingAssets @An extension to the BuildReport class that tracks which scenes in the build have references to a specific asset in the build.
---@field list fun() @An array of ScenesUsingAsset that holds information about the Assets that are included in the build.
