---@class Build.Player.TypeDB @Container for holding information about script type and property data.
---@field GetHash128 fun() @Gets the hash for the BuildReferenceMap.
---@field GetObjectData fun() @ISerializable method for serialization support outside of Unity's internal serialization system.
---@field Dispose fun() @Dispose the TypeDB destroying all internal state.
---@field GetHashCode fun() @Gets the hash code for the TypeDB.
---@field Equals fun() @Returns true if the objects are equal.
