---@class Build.Reporting.BuildStepMessage @Contains information about a single log message recorded during the build process.
---@field content fun() @The text content of the log message.
---@field type fun() @The LogType of the log message.
