---@class Build.IActiveBuildTargetChanged @Implement this interface to receive a callback after the active build platform has changed.
---@field OnActiveBuildTargetChanged fun() @This function is called automatically when the active build platform has changed.
