---@class Callbacks.OnOpenAssetAttributeMode @Indicates whether OnOpenAssetAttribute decorated method is a validation function that checks if asset opening is handled by Unity or a custom script.
---@field Execute fun() @Indicates that OnOpenAssetAttribute decorated method is an opening function.
---@field Validate fun() @Indicates that OnOpenAssetAttribute decorated method is a validation function.
