---@class Callbacks.RunBeforeAssemblyAttribute @Add this attribute to a callback method to indicate that this callback must be run before any callbacks that are part of the specified assembly.
---@field ctor fun() @Add this attribute to a callback method to indicate that this callback must be run before any callbacks that are part of the specified assembly.
---@field assemblyName fun() @The name of the assembly that should be called after this callback.
