---@class Camera.FieldOfViewAxis @Enumerates which axis to use when expressing the value for the field of view.                The default value is Camera.FieldOfViewAxis.Vertical.
---@field Vertical fun() @Specifies the field of view as vertical.
---@field Horizontal fun() @Specifies the field of view as horizontal.
