---@class Camera.GateFitParameters @Wrapper for gate fit parameters
---@field mode fun() @GateFitMode to use. See Camera.GateFitMode.
---@field ctor fun() @Wrapper for gate fit parameters.
---@field aspect fun() @Aspect ratio of the resolution gate.
