---@class CameraEditor @Unity Camera Editor.
---@field OnDestroy fun() @See ScriptableObject.OnDestroy.
---@field OnSceneGUI fun() @See Editor.OnSceneGUI.
---@field Settings CameraEditor.Settings @Contains all drawable elements of the CameraEditor.
---@field settings fun() @Settings for the camera editor.
---@field OnEnable fun() @See ScriptableObject.OnEnable.
---@field OnDisable fun() @See ScriptableObject.OnDisable.
---@field OnInspectorGUI fun() @See Editor.OnInspectorGUI.
