---@class CapsuleCollider2D @A capsule-shaped primitive collider.
---@field direction fun() @The direction that the capsule sides can extend.
---@field size fun() @The width and height of the capsule area.
