---@class ClipAnimationMaskType @AnimationClip mask options for ModelImporterClipAnimation.
---@field None fun() @No Mask. All the animation will be imported.
---@field CopyFromOther fun() @Use a mask from your project to specify which transforms animation should be imported.
---@field CreateFromThisModel fun() @A mask containing all the transform in the file will be created internally.
