---@class ColorGamut @Represents a color gamut.
---@field HDR10 fun() @HDR10 high dynamic range color gamut.
---@field sRGB fun() @sRGB color gamut.
---@field DisplayP3 fun() @Display-P3 color gamut.
---@field Rec2020 fun() @Rec. 2020 color gamut.
---@field DolbyHDR fun() @DolbyHDR high dynamic range color gamut.
---@field Rec709 fun() @Rec. 709 color gamut.
