---@class Compilation.CodeOptimization @Code optimization mode defines whether UnityEditor compiles scripts in Debug or Release mode.
---@field None fun() @Unitialized value for code optimization mode.
---@field Debug fun() @Debug mode enables C# debugging but reduces C# performance.
---@field Release fun() @Release mode disables C# debugging but improves C# performance.
