---@class Compilation @nil
---@field AssemblyDefinitionException Compilation.AssemblyDefinitionException @An exception throw for Assembly Definition Files errors.
---@field AssemblyDefinitionPlatform Compilation.AssemblyDefinitionPlatform @Contains information about a platform supported by the assembly definition files.
---@field AssembliesType Compilation.AssembliesType @Flags for Assembly.
---@field ReferencesOptions Compilation.ReferencesOptions @Options to control the Unity References to other assembly definition files that Unity uses during compilation.
---@field AssemblyBuilderStatus Compilation.AssemblyBuilderStatus @Status of the AssemblyBuilder build.
---@field Assembly Compilation.Assembly @Class that represents an assembly compiled by Unity.
---@field PrecompiledAssemblyException Compilation.PrecompiledAssemblyException @An exception throw for Precompiled Assembly errors.
---@field ScriptCompilerOptions Compilation.ScriptCompilerOptions @Compiler options passed to the script compiler.
---@field AssemblyFlags Compilation.AssemblyFlags @Flags for Assembly.
---@field AssemblyBuilder Compilation.AssemblyBuilder @Compiles scripts outside the Assets folder into a managed assembly that can be used inside the Assets folder.
---@field ResponseFileData Compilation.ResponseFileData @Data class used for storing parsed response file data.
---@field CompilationPipeline Compilation.CompilationPipeline @Methods and properties for script compilation pipeline.
---@field RequestScriptCompilationOptions Compilation.RequestScriptCompilationOptions @Options for specifying the behavior of CompilationPipeline.RequestScriptCompilation.
---@field CompilerMessage Compilation.CompilerMessage @Compiler Message.
---@field AssemblyDefinitionReferenceType Compilation.AssemblyDefinitionReferenceType @Assembly definition file reference type.
---@field CompilerMessageType Compilation.CompilerMessageType @Compiler message type.
---@field CodeOptimization Compilation.CodeOptimization @Code optimization mode defines whether UnityEditor compiles scripts in Debug or Release mode.
---@field AssemblyBuilderFlags Compilation.AssemblyBuilderFlags @Flags used by  AssemblyBuilder to control assembly build.
