---@class CreateAssetMenuAttribute @Mark a ScriptableObject-derived type to be automatically listed in the Assets/Create submenu, so that instances of the type can be easily created and stored in the project as .asset files.
---@field order fun() @The position of the menu item within the Assets/Create menu.
---@field menuName fun() @The display name for this type shown in the Assets/Create menu.
---@field fileName fun() @The default file name used by newly created instances of this type.
