---@class CullingGroupEvent @Provides information about the current and previous states of one sphere in a CullingGroup.
---@field wasVisible fun() @Was the sphere visible before the most recent culling pass?
---@field hasBecomeVisible fun() @Did this sphere change from being invisible to being visible in the most recent culling pass?
---@field hasBecomeInvisible fun() @Did this sphere change from being visible to being invisible in the most recent culling pass?
---@field previousDistance fun() @The distance band index of the sphere before the most recent culling pass.
---@field currentDistance fun() @The current distance band index of the sphere, after the most recent culling pass.
---@field index fun() @The index of the sphere that has changed.
---@field isVisible fun() @Was the sphere considered visible by the most recent culling pass?
