---@class CursorLockMode @How the cursor should behave.
---@field Confined fun() @Confine cursor to the game window.
---@field Locked fun() @Lock cursor to the center of the game window.
---@field None fun() @Cursor behavior is unmodified.
