---@class CustomRenderTextureInitializationSource @Specify the source of a Custom Render Texture initialization.
---@field Material fun() @Custom Render Texture is initalized with a Material.
---@field TextureAndColor fun() @Custom Render Texture is initialized by a Texture multiplied by a Color.
