---@class DeviceSimulation.DeviceSimulator @Class for interacting with a Device Simulator window from a script.
---@field touchScreenInput fun() @Event invoked when the screen of the simulated device is clicked.
