---@class Device.Screen @Access platform-specific display information.
---@field safeArea fun() @This has the same functionality as Screen.safeArea and also mimics platform-specific behavior in the Unity Editor.
---@field fullScreenMode fun() @This has the same functionality as Screen.fullScreenMode and also mimics platform-specific behavior in the Unity Editor.
---@field cutouts fun() @This has the same functionality as Screen.cutouts and also mimics platform-specific behavior in the Unity Editor.
---@field width fun() @This has the same functionality as Screen.width and also mimics platform-specific behavior in the Unity Editor.
---@field autorotateToLandscapeRight fun() @This has the same functionality as Screen.autorotateToLandscapeRight and also mimics platform-specific behavior in the Unity Editor.
---@field resolutions fun() @This has the same functionality as Screen.resolutions and also mimics platform-specific behavior in the Unity Editor.
---@field mainWindowDisplayInfo fun() @The Device Simulator doesn't simulate this property.
---@field fullScreen fun() @This has the same functionality as Screen.fullScreen and also mimics platform-specific behavior in the Unity Editor.
---@field height fun() @This has the same functionality as Screen.height and also mimics platform-specific behavior in the Unity Editor.
---@field dpi fun() @This has the same functionality as Screen.dpi and also mimics platform-specific behavior in the Unity Editor.
---@field brightness fun() @This has the same functionality as Screen.brightness. At the moment, the Device Simulator doesn't support simulation of this property.
---@field sleepTimeout fun() @This has the same functionality as Screen.sleepTimeout. At the moment, the Device Simulator doesn't support simulation of this property.
---@field autorotateToPortraitUpsideDown fun() @This has the same functionality as Screen.autorotateToPortraitUpsideDown and also mimics platform-specific behavior in the Unity Editor.
---@field mainWindowPosition fun() @The Device Simulator doesn't simulate this property.
---@field autorotateToLandscapeLeft fun() @This has the same functionality as Screen.autorotateToLandscapeLeft and also mimics platform-specific behavior in the Unity Editor.
---@field SetResolution fun() @This has the same functionality as Screen.SetResolution and also mimics platform-specific behavior in the Unity Editor.
---@field GetDisplayLayout fun() @The Device Simulator doesn't simulate this property.
---@field orientation fun() @This has the same functionality as Screen.orientation and also mimics platform-specific behavior in the Unity Editor.
---@field currentResolution fun() @This has the same functionality as Screen.currentResolution and also mimics platform-specific behavior in the Unity Editor.
---@field MoveMainWindowTo fun() @The Device Simulator doesn't simulate this method.
---@field autorotateToPortrait fun() @This has the same functionality as Screen.autorotateToPortrait and also mimics platform-specific behavior in the Unity Editor.
