---@class EditorSettings.NamingScheme @Which naming scheme to use for duplicated GameObjects.
---@field SpaceParenthesis fun() @Adds a space and a number in parenthesis to the name of an instantiated or duplicated GameObject (Prefab (1)).
---@field Underscore fun() @Adds an underscore and a number to the name of an instantiated or duplicated GameObject (Prefab_1).
---@field Dot fun() @Adds a dot followed by a number to the name of an instantiated or duplicated GameObject (Prefab.1).
