---@class EditorWindowTitleAttribute @Use this class to set title text and icon for an Editor window.
---@field title fun() @Specifies an Editor window's title text.
---@field ctor fun() @Creates Editor window title content.
---@field icon fun() @Specifies the path to an Editor window's default icon.
---@field useTypeNameAsIconName fun() @When set to true Unity sets the window's icon name to be the same as its type name.
