---@class EditorGUILayout.VerticalScope @Disposable helper class for managing BeginVertical / EndVertical.
---@field ctor fun() @Create a new VerticalScope and begin the corresponding vertical group.
---@field rect fun() @The rect of the vertical group.
