---@class EditorJsonUtility @Utility functions for working with JSON data and engine objects.
---@field ToJson fun() @Generate a JSON representation of an object.
---@field FromJsonOverwrite fun() @Overwrite data in an object by reading from its JSON representation.
