---@class Experimental.GraphView.GraphViewBlackboardWindow @The base class for a floating window that contains a Blackboard.
---@field OnGraphViewChanging fun() @Callback invoked when the GraphView is about to change.
---@field ctor fun() @Constructor.
---@field ToolName fun() @The tool window name.
---@field IsGraphViewSupported fun() @Verifies whether the GraphView tool window supports a specific GraphView.
---@field OnGraphViewChanged fun() @Callback invoked when the GraphView has changed.
