---@class Experimental.GraphView.FreehandSelector @Freehand selection tool.
---@field RegisterCallbacksOnTarget fun() @Register callbacks on target VisualElement.
---@field ctor fun() @FreehandSelector constructor.
---@field UnregisterCallbacksFromTarget fun() @Unregister callbacks on target VisualElement.
