---@class Experimental.GraphView.StickyNoteTheme @Enum used to describe the visual theme used by the [StickyNote].
---@field Black fun() @The dark theme.
---@field Classic fun() @The light, classic theme.
