---@class Experimental.GlobalIllumination.LightmapperUtils @Utility class for converting Unity Lights to light types recognized by the baking backends.
---@field Extract fun() @Extracts informations from Lights.
---@field ExtractInnerCone fun() @Extracts the inner cone angle of spot lights.
---@field ExtractIndirect fun() @Extracts the indirect color from a light.
