---@class Experimental.AI @nil
---@field NavMeshLocation Experimental.AI.NavMeshLocation @A world position that is guaranteed to be on the surface of the NavMesh.
---@field NavMeshPolyTypes Experimental.AI.NavMeshPolyTypes @The types of nodes in the navigation data.
---@field NavMeshWorld Experimental.AI.NavMeshWorld @Assembles together a collection of NavMesh surfaces and links that are used as a whole for performing navigation operations.
---@field PathQueryStatus Experimental.AI.PathQueryStatus @Bit flags representing the resulting state of NavMeshQuery operations.
---@field NavMeshQuery Experimental.AI.NavMeshQuery @Object used for doing navigation operations in a NavMeshWorld.
---@field PolygonId Experimental.AI.PolygonId @Represents a compact identifier for the data of a NavMesh node.
