---@class Experimental @nil
---@field ArtifactID Experimental.ArtifactID @Uniquely identifies a produced artifact such as an imported asset (e.g. result of importing a texture).
---@field Lightmapping Experimental.Lightmapping @Experimental lightmapping features.
---@field Video Experimental.Video @nil
---@field Audio fun() @nil
---@field RenderSettings Experimental.RenderSettings @Experimental render settings features.
---@field Licensing fun() @nil
---@field Rendering Experimental.Rendering @nil
---@field Playables Experimental.Playables @nil
---@field ArtifactKey Experimental.ArtifactKey @An ArtifactKey is used for specifying an artifact to lookup or produce.
---@field Animations Experimental.Animations @nil
---@field GlobalIllumination Experimental.GlobalIllumination @nil
---@field GraphView Experimental.GraphView @nil
---@field AI Experimental.AI @nil
