---@class Experimental.GraphView.ISelectable @Selectable interface.
---@field IsSelected fun() @Check if element is selected.
---@field Overlaps fun() @Check if selection overlaps rectangle.
---@field Select fun() @Select element.
---@field HitTest fun() @See if point is on target.
---@field IsSelectable fun() @Check if element is selectable.
---@field Unselect fun() @Deselect element.
