---@class Experimental.Rendering.ScriptableRuntimeReflectionSystemSettings @Global settings for the scriptable runtime reflection system.
---@field system fun() @The current scriptable runtime reflection system instance.
