---@class Experimental.GlobalIllumination.RenderSettings @Experimental render settings features.
---@field useRadianceAmbientProbe fun() @If enabled, ambient trilight will be sampled using the old radiance sampling method.
