---@class Experimental.GraphView.ICollectibleElement @CollectibleElement interface.
---@field CollectElements fun() @Retrieves a set of graph elements that match a specified condition. The graph elements are collected from the elements associated with implementor of this interface.
