---@class FilePathAttribute @An attribute that specifies a file location relative to the Project folder or Unity's preferences folder. See Also: FilePathAttribute.Location.
---@field ctor fun() @
---@field Location FilePathAttribute.Location @Specifies the folder location that Unity uses together with the relative path provided in the FilePathAttribute constructor.
