---@class FontTextureCase @Texture case constants for TrueTypeFontImporter.
---@field ASCII fun() @Import basic ASCII character set.
---@field ASCIILowerCase fun() @Only import lower case ASCII character set.
---@field Unicode fun() @Import a set of Unicode characters common for latin scripts.
---@field Dynamic fun() @Render characters into font texture at runtime as needed.
---@field ASCIIUpperCase fun() @Only import upper case ASCII character set.
---@field CustomSet fun() @Custom set of characters.
