---@class ForceMode2D @Option for how to apply a force using Rigidbody2D.AddForce.
---@field Impulse fun() @Add an instant force impulse to the rigidbody2D, using its mass.
---@field Force fun() @Add a force to the Rigidbody2D, using its mass.
