---@class FullScreenMovieScalingMode @Describes scaling modes for displaying movies.
---@field AspectFit fun() @Scale the movie until one dimension fits on the screen exactly.
---@field None fun() @Do not scale the movie.
---@field AspectFill fun() @Scale the movie until the movie fills the entire screen.
---@field Fill fun() @Scale the movie until both dimensions fit the screen exactly.
