---@class GamepadSpeakerOutputType @Gamepad audio output types.
---@field Speaker fun() @Audio output is through the gamepads audio speaker if the gamepad supports playing audio.
---@field Vibration fun() @Audio output is through the gamepads vibration device if the gamepad supports playing audio as vibration.
---@field SecondaryVibration fun() @Audio output is through a secondary gamepad's vibration device if supported.
