---@class GradientUsageAttribute @Attribute used to configure the usage of the GradientField and Gradient Editor for a gradient.
---@field colorSpace fun() @The color space the Gradient uses.
---@field ctor fun() @Attribute for gradient fields. Used to configure the GUI for the Gradient Editor.
---@field hdr fun() @If set to true the Gradient uses HDR colors.
