---@class GUILayoutUtility @Utility functions for implementing and extending the GUILayout class.
---@field GetAspectRect fun() @Reserve layout space for a rectangle with a specific aspect ratio.
---@field GetRect fun() @Reserve layout space for a rectangle for displaying some contents with a specific style.
---@field GetLastRect fun() @Get the rectangle last used by GUILayout for a control.
