---@class HeadDof @Enumeration of all the muscles in the head.
---@field LastHeadDof fun() @The last value of the HeadDof enum.
---@field NeckFrontBack fun() @The neck front-back muscle.
---@field NeckLeftRight fun() @The neck left-right muscle.
---@field RightEyeInOut fun() @The right eye in-out muscle.
---@field HeadRollLeftRight fun() @The head roll left-right muscle.
---@field LeftEyeDownUp fun() @The left eye down-up muscle.
---@field RightEyeDownUp fun() @The right eye down-up muscle.
---@field HeadFrontBack fun() @The head front-back muscle.
---@field JawDownUp fun() @The jaw down-up muscle.
---@field HeadLeftRight fun() @The head left-right muscle.
---@field JawLeftRight fun() @The jaw left-right muscle.
---@field NeckRollLeftRight fun() @The neck roll left-right muscle.
---@field LeftEyeInOut fun() @The left eye in-out muscle.
