---@class Help @Helper class to access Unity documentation.
---@field HasHelpForObject fun() @Is there a help page for this object?
---@field GetHelpURLForObject fun() @Get the URL for this object's documentation.
---@field ShowHelpPage fun() @Show a help page.
---@field ShowHelpForObject fun() @Show help page for this object.
---@field BrowseURL fun() @Open url in the default web browser.
