---@class HumanTrait @Details of all the human bone and muscle types defined by Mecanim.
---@field MuscleFromBone fun() @Obtain the muscle index for a particular bone index and degree of freedom.
---@field BoneCount fun() @The number of human bone types defined by Mecanim.
---@field GetMuscleDefaultMin fun() @Get the default minimum value of rotation for a muscle in degrees.
---@field RequiredBone fun() @Is the bone a member of the minimal set of bones that Mecanim requires for a human model?
---@field RequiredBoneCount fun() @The number of bone types that are required by Mecanim for any human model.
---@field MuscleName fun() @Array of the names of all human muscle types defined by Mecanim.
---@field GetMuscleDefaultMax fun() @Get the default maximum value of rotation for a muscle in degrees.
---@field BoneFromMuscle fun() @Return the bone to which a particular muscle is connected.
---@field GetParentBone fun() @Returns parent humanoid bone index of a bone.
---@field GetBoneDefaultHierarchyMass fun() @Gets the bone hierarchy mass.
---@field MuscleCount fun() @The number of human muscle types defined by Mecanim.
---@field BoneName fun() @Array of the names of all human bone types defined by Mecanim.
