---@class HumanPose @Retargetable humanoid pose.
---@field bodyPosition fun() @The human body position for that pose.
---@field muscles fun() @The array of muscle values for that pose.
---@field bodyRotation fun() @The human body orientation for that pose.
