---@class HumanBodyBones @Human Body Bones.
---@field LeftThumbDistal fun() @This is the left thumb 3rd phalange.
---@field LastBone fun() @This is the Last bone index delimiter.
---@field RightMiddleDistal fun() @This is the right middle 3rd phalange.
---@field LeftMiddleDistal fun() @This is the left middle 3rd phalange.
---@field LeftLittleDistal fun() @This is the left little 3rd phalange.
---@field Hips fun() @This is the Hips bone.
---@field LeftShoulder fun() @This is the Left Shoulder bone.
---@field Neck fun() @This is the Neck bone.
---@field LeftThumbProximal fun() @This is the left thumb 1st phalange.
---@field LeftIndexIntermediate fun() @This is the left index 2nd phalange.
---@field RightRingProximal fun() @This is the right ring 1st phalange.
---@field LeftEye fun() @This is the Left Eye bone.
---@field RightRingIntermediate fun() @This is the right ring 2nd phalange.
---@field LeftMiddleIntermediate fun() @This is the left middle 2nd phalange.
---@field LeftThumbIntermediate fun() @This is the left thumb 2nd phalange.
---@field RightShoulder fun() @This is the Right Shoulder bone.
---@field RightUpperLeg fun() @This is the Right Upper Leg bone.
---@field RightUpperArm fun() @This is the Right Upper Arm bone.
---@field RightToes fun() @This is the Right Toes bone.
---@field RightThumbProximal fun() @This is the right thumb 1st phalange.
---@field RightThumbIntermediate fun() @This is the right thumb 2nd phalange.
---@field RightFoot fun() @This is the Right Ankle bone.
---@field Spine fun() @This is the first Spine bone.
---@field RightLittleDistal fun() @This is the right little 3rd phalange.
---@field UpperChest fun() @This is the Upper Chest bone.
---@field LeftRingProximal fun() @This is the left ring 1st phalange.
---@field RightRingDistal fun() @This is the right ring 3rd phalange.
---@field RightHand fun() @This is the Right Wrist bone.
---@field RightMiddleIntermediate fun() @This is the right middle 2nd phalange.
---@field LeftLowerLeg fun() @This is the Left Knee bone.
---@field RightLowerLeg fun() @This is the Right Knee bone.
---@field RightLowerArm fun() @This is the Right Elbow bone.
---@field RightLittleProximal fun() @This is the right little 1st phalange.
---@field Head fun() @This is the Head bone.
---@field Chest fun() @This is the Chest bone.
---@field LeftRingIntermediate fun() @This is the left ring 2nd phalange.
---@field RightLittleIntermediate fun() @This is the right little 2nd phalange.
---@field LeftUpperLeg fun() @This is the Left Upper Leg bone.
---@field LeftRingDistal fun() @This is the left ring 3rd phalange.
---@field RightIndexIntermediate fun() @This is the right index 2nd phalange.
---@field LeftHand fun() @This is the Left Wrist bone.
---@field RightMiddleProximal fun() @This is the right middle 1st phalange.
---@field LeftToes fun() @This is the Left Toes bone.
---@field LeftLowerArm fun() @This is the Left Elbow bone.
---@field LeftFoot fun() @This is the Left Ankle bone.
---@field LeftIndexDistal fun() @This is the left index 3rd phalange.
---@field RightThumbDistal fun() @This is the right thumb 3rd phalange.
---@field RightEye fun() @This is the Right Eye bone.
---@field LeftMiddleProximal fun() @This is the left middle 1st phalange.
---@field LeftLittleIntermediate fun() @This is the left little 2nd phalange.
---@field LeftLittleProximal fun() @This is the left little 1st phalange.
---@field Jaw fun() @This is the Jaw bone.
---@field RightIndexDistal fun() @This is the right index 3rd phalange.
---@field LeftUpperArm fun() @This is the Left Upper Arm bone.
---@field RightIndexProximal fun() @This is the right index 1st phalange.
---@field LeftIndexProximal fun() @This is the left index 1st phalange.
