---@class IAnimationClipSource @Use this interface to have a class provide its own list of Animation Clips to the Animation Window.  The class must inherit from MonoBehaviour.
---@field GetAnimationClips fun() @Returns a list of Animation Clips.
