---@class IconKind @Icon kind.
---@field Application fun() @This icon is used for the main application icons.
---@field Store fun() @This icon is used by the iOS App Store.
---@field Spotlight fun() @This icon is used for Spotlight searches. (iOS only).
---@field Notification fun() @This icon is used for push notifications.
---@field Settings fun() @This icon is used for settings.
---@field Any fun() @This icon can be used for any purpose in an application.
