---@class iOS.Xcode.PBXSourceTree @Specifies source trees for files.
---@field Source fun() @The file path is relative to the project path.
---@field Developer fun() @The file path is relative to the developer directory.
---@field Group fun() @The file path is relative to the group the file is in.
---@field Absolute fun() @The file path is absolute path.
---@field Sdk fun() @The file path is relative to SDK path.
---@field Build fun() @The file path is relative to build products path.
