---@class iOS.DeviceGeneration @iOS device generation.
---@field iPadPro11Inch2Gen fun() @iPad Pro 11, second generation.
---@field iPad5Gen fun() @iPad, fifth generation.
---@field iPad9Gen fun() @iPad, ninth generation.
---@field iPadPro5Gen fun() @iPad Pro 12.9, fifth generation.
---@field iPadPro2Gen fun() @iPad Pro 12.9, second generation.
---@field iPad8Gen fun() @iPad, eighth generation.
---@field iPadUnknown fun() @Yet unknown iPad.
---@field iPhone6SPlus fun() @iPhone 6S Plus.
---@field iPadPro3Gen fun() @iPad Pro 12.9, third generation.
---@field iPhone5 fun() @iPhone5.
---@field iPhone3GS fun() @iPhone, third generation.
---@field iPhoneX fun() @iPhone X.
---@field iPhone6 fun() @iPhone 6.
---@field iPhone11ProMax fun() @iPhone 11 Pro Max.
---@field iPhone fun() @iPhone, first generation.
---@field iPhone11 fun() @iPhone 11.
---@field iPadAir3Gen fun() @iPad Air, third generation.
---@field iPhone12 fun() @iPhone 12.
---@field iPadAir2 fun() @iPad Air 2.
---@field iPadMini4Gen fun() @iPad Mini, fourth generation.
---@field iPodTouch5Gen fun() @iPod Touch, fifth generation.
---@field iPhone7 fun() @iPhone 7.
---@field iPhone12ProMax fun() @iPhone 12 Pro Max.
---@field iPodTouchUnknown fun() @Yet unknown iPod Touch.
---@field iPhoneXS fun() @iPhone XS.
---@field iPhone6Plus fun() @iPhone 6 plus.
---@field iPadPro4Gen fun() @iPad Pro 12.9, fourth generation.
---@field iPhone12Pro fun() @iPhone 12 Pro.
---@field iPodTouch2Gen fun() @iPod Touch, second generation.
---@field iPhoneXR fun() @iPhone XR.
---@field iPodTouch6Gen fun() @iPod Touch, sixth generation.
---@field iPhone11Pro fun() @iPhone 11 Pro.
---@field iPhone5C fun() @iPhone 5C.
---@field iPhone13Mini fun() @iPhone 13 Mini.
---@field iPhoneUnknown fun() @Yet unknown iPhone.
---@field iPadAir5Gen fun() @iPad Air, fifth generation.
---@field iPhone13 fun() @iPhone 13.
---@field iPad6Gen fun() @iPad, sixth generation.
---@field iPadAir4Gen fun() @iPad Air, fourth generation.
---@field iPadPro10Inch1Gen fun() @iPad Pro 9.7, first generation.
---@field iPhoneXSMax fun() @iPhone XSMax.
---@field iPhone4 fun() @iPhone, fourth generation.
---@field iPadPro11Inch fun() @iPad Pro 11, first generation.
---@field iPhoneSE2Gen fun() @iPhone SE, second generation.
---@field iPadPro1Gen fun() @iPad Pro 12.9, first generation.
---@field iPodTouch4Gen fun() @iPod Touch, fourth generation.
---@field iPhone8Plus fun() @iPhone 8 Plus.
---@field iPad7Gen fun() @iPad, seventh generation.
---@field iPhoneSE1Gen fun() @iPhone SE, first generation.
---@field iPadMini1Gen fun() @iPad Mini, first generation.
---@field iPhone13ProMax fun() @iPhone 13 Pro Max.
---@field iPadAir1 fun() @iPad Air.
---@field iPodTouch7Gen fun() @iPod Touch, seventh generation.
---@field iPadMini3Gen fun() @iPad Mini, third generation.
---@field iPodTouch3Gen fun() @iPod Touch, third generation.
---@field iPhone3G fun() @iPhone, second generation.
---@field iPodTouch1Gen fun() @iPod Touch, first generation.
---@field iPadMini2Gen fun() @iPad Mini, second generation.
---@field iPhone8 fun() @iPhone 8.
---@field iPhoneSE3Gen fun() @iPhone SE, third generation.
---@field iPad2Gen fun() @iPad, second generation.
---@field iPad3Gen fun() @iPad, third generation.
---@field iPad4Gen fun() @iPad, fourth generation.
---@field iPadMini5Gen fun() @iPad Mini, fifth generation.
---@field iPhone7Plus fun() @iPhone 7 Plus.
---@field iPhone12Mini fun() @iPhone 12 Mini.
---@field iPadPro11Inch3Gen fun() @iPad Pro 11, third generation.
---@field iPhone5S fun() @iPhone 5S.
---@field iPhone4S fun() @iPhone, fifth generation.
---@field iPhone6S fun() @iPhone 6S.
---@field iPad1Gen fun() @iPad, first generation.
---@field iPhone13Pro fun() @iPhone 13 Pro.
---@field iPadMini6Gen fun() @iPad Mini, sixth generation.
---@field iPadPro10Inch2Gen fun() @iPad Pro 10.5, second generation 10 iPad.
