---@class iOS.Xcode.PlistElement @Represents a plist element.
---@field AsArray fun() @Convenience function to convert to array element.
---@field AsInteger fun() @Convenience function to convert to integer.
---@field Index_operator fun() @Convenience method to access properties of a dictionary element.
---@field AsBoolean fun() @Convenience function to convert to bool.
---@field AsDate fun() @Convenience function to convert to date.
---@field AsReal fun() @Convenience function to convert to float.
---@field AsString fun() @Convenience function to convert to string.
---@field AsDict fun() @Convenience function to convert to dictionary element.
