---@class iOS.iOSPlatformIconKind @Contains all iOS PlatformIconKind supported by Unity.
---@field Application fun() @This is the icon displayed on the iOS home screen.
---@field Spotlight fun() @This is the icon displayed in Spotlight search results.
---@field Notification fun() @This is the icon displayed in notifications sent by the app.
---@field Settings fun() @This is the icon displayed in settings if the app contains a settings bundle.
---@field Marketing fun() @This is the icon displayed on the app's App Store page.
