---@class iOS @nil
---@field Xcode iOS.Xcode @nil
---@field DeviceGeneration iOS.DeviceGeneration @iOS device generation.
---@field ADBannerView iOS.ADBannerView @ADBannerView is a wrapper around the ADBannerView class found in the Apple iAd framework and is only available on iOS.
---@field NotificationServices iOS.NotificationServices @NotificationServices is only available on iPhone/iPad/iPod Touch.
---@field ActivityIndicatorStyle iOS.ActivityIndicatorStyle @ActivityIndicator Style (iOS Specific).
---@field ADInterstitialAd iOS.ADInterstitialAd @ADInterstitialAd is a wrapper around the ADInterstitialAd class found in the Apple iAd framework and is only available on iPad.
---@field LocalNotification iOS.LocalNotification @iOS.LocalNotification is a wrapper around the UILocalNotification class found in the Apple UIKit framework and is only available on iPhone/iPad/iPod Touch.
---@field SystemGestureDeferMode iOS.SystemGestureDeferMode @Bit-mask used to control the deferring of system gestures on iOS.
---@field Device iOS.Device @Interface into iOS specific functionality.
---@field OnDemandResourcesRequest iOS.OnDemandResourcesRequest @Represents a request for On Demand Resources (ODR). It's an AsyncOperation and can be yielded in a coroutine.
---@field OnDemandResources iOS.OnDemandResources @On Demand Resources API.
---@field NotificationType iOS.NotificationType @Specifies local and remote notification types.
---@field iOSPlatformIconKind iOS.iOSPlatformIconKind @Contains all iOS PlatformIconKind supported by Unity.
---@field CalendarIdentifier iOS.CalendarIdentifier @Specify calendar types.
---@field RemoteNotification iOS.RemoteNotification @RemoteNotification is only available on iPhone/iPad/iPod Touch.
---@field CalendarUnit iOS.CalendarUnit @Specify calendrical units.
