---@class iOSBackgroundMode @Background modes supported by the application corresponding to project settings in Xcode.
---@field BluetoothCentral fun() @Uses Bluetooth LE accessories.
---@field VOIP fun() @Voice over IP.
---@field None fun() @No background modes supported.
---@field BluetoothPeripheral fun() @Acts as a Bluetooth LE accessory.
---@field NewsstandContent fun() @Newsstand downloads.
---@field ExternalAccessory fun() @External accessory communication.
---@field Location fun() @Location updates.
---@field Audio fun() @Audio, AirPlay and Picture in Picture.
---@field RemoteNotification fun() @Remote notifications.
---@field Fetch fun() @Background fetch.
