---@class iOSDeviceRequirement @A device requirement description used for configuration of App Slicing.
---@field values fun() @The values of the device requirement description.
---@field ctor fun() @Constructs new device requirement description.
