---@class iOSLaunchScreenImageType @iOS launch screen settings.
---@field iPhonePortraitImage fun() @Portrait oriented launch screen image on the iPhone.
---@field iPhoneLandscapeImage fun() @Landscape oriented launch screen image on the iPhone.
---@field iPadImage fun() @Launch screen image on the iPad.
