---@class Jobs.TransformAccessArray @TransformAccessArray.
---@field Allocate fun() @Allocate.
---@field ctor fun() @Constructor.
---@field Add fun() @Add.
---@field SetTransforms fun() @Set transforms.
---@field RemoveAtSwapBack fun() @Remove item at index.
---@field Index_operator fun() @Array indexer.
---@field length fun() @Length.
---@field Dispose fun() @Dispose.
---@field isCreated fun() @isCreated.
---@field capacity fun() @Returns array capacity.
