---@class JointLimitState2D @Represents the state of a joint limit.
---@field LowerLimit fun() @Represents a state where the joint limit is at the specified lower limit.
---@field EqualLimits fun() @Represents a state where the joint limit is at the specified lower and upper limits (they are identical).
---@field Inactive fun() @Represents a state where the joint limit is inactive.
---@field UpperLimit fun() @Represents a state where the joint limit is at the specified upper limit.
