---@class JointMotor2D @Parameters for the optional motor force applied to a Joint2D.
---@field maxMotorTorque fun() @The maximum force that can be applied to the Rigidbody2D at the joint to attain the target speed.
---@field motorSpeed fun() @The desired speed for the Rigidbody2D to reach as it moves with the joint.
