---@class KeyCode @Key codes returned by Event.keyCode. These map directly to a physical key on the keyboard.
---@field Joystick4Button10 fun() @Button 10 on forth joystick.
---@field Joystick6Button2 fun() @Button 2 on sixth joystick.
---@field Joystick7Button10 fun() @Button 10 on seventh joystick.
---@field Hash fun() @Hash key '#'.
---@field Keypad6 fun() @Numeric keypad 6.
---@field Joystick7Button14 fun() @Button 14 on seventh joystick.
---@field Joystick7Button2 fun() @Button 2 on seventh joystick.
---@field Joystick2Button17 fun() @Button 17 on second joystick.
---@field Joystick1Button1 fun() @Button 1 on first joystick.
---@field Home fun() @Home key.
---@field Joystick1Button15 fun() @Button 15 on first joystick.
---@field JoystickButton1 fun() @Button 1 on any joystick.
---@field F4 fun() @F4 function key.
---@field F15 fun() @F15 function key.
---@field Joystick1Button10 fun() @Button 10 on first joystick.
---@field Joystick7Button18 fun() @Button 18 on seventh joystick.
---@field JoystickButton4 fun() @Button 4 on any joystick.
---@field Joystick4Button6 fun() @Button 6 on forth joystick.
---@field Alpha0 fun() @The '0' key on the top of the alphanumeric keyboard.
---@field Joystick3Button9 fun() @Button 9 on third joystick.
---@field Joystick7Button16 fun() @Button 16 on seventh joystick.
---@field Joystick4Button19 fun() @Button 19 on forth joystick.
---@field Joystick5Button12 fun() @Button 12 on fifth joystick.
---@field Joystick6Button18 fun() @Button 18 on sixth joystick.
---@field Joystick5Button5 fun() @Button 5 on fifth joystick.
---@field Tab fun() @The tab key.
---@field Alpha3 fun() @The '3' key on the top of the alphanumeric keyboard.
---@field F7 fun() @F7 function key.
---@field Joystick3Button17 fun() @Button 17 on third joystick.
---@field Keypad8 fun() @Numeric keypad 8.
---@field F13 fun() @F13 function key.
---@field Joystick5Button18 fun() @Button 18 on fifth joystick.
---@field SysReq fun() @Sys Req key.
---@field Keypad0 fun() @Numeric keypad 0.
---@field Joystick8Button12 fun() @Button 12 on eighth joystick.
---@field Joystick8Button2 fun() @Button 2 on eighth joystick.
---@field Joystick4Button15 fun() @Button 15 on forth joystick.
---@field Joystick8Button19 fun() @Button 19 on eighth joystick.
---@field Joystick1Button8 fun() @Button 8 on first joystick.
---@field Joystick4Button12 fun() @Button 12 on forth joystick.
---@field Joystick7Button1 fun() @Button 1 on seventh joystick.
---@field F6 fun() @F6 function key.
---@field Joystick2Button12 fun() @Button 12 on second joystick.
---@field PageDown fun() @Page down.
---@field Joystick5Button15 fun() @Button 15 on fifth joystick.
---@field JoystickButton2 fun() @Button 2 on any joystick.
---@field Quote fun() @Quote key '.
---@field Return fun() @Return key.
---@field Joystick2Button7 fun() @Button 7 on second joystick.
---@field Insert fun() @Insert key key.
---@field RightMeta fun() @Maps to right Windows key or right Command key if physical keys are enabled in Input Manager settings, otherwise maps to right Command key only.
---@field Joystick3Button0 fun() @Button 0 on third joystick.
---@field Joystick4Button1 fun() @Button 1 on forth joystick.
---@field Joystick5Button3 fun() @Button 3 on fifth joystick.
---@field Joystick1Button7 fun() @Button 7 on first joystick.
---@field Joystick5Button2 fun() @Button 2 on fifth joystick.
---@field Help fun() @Help key.
---@field Joystick6Button3 fun() @Button 3 on sixth joystick.
---@field Joystick3Button16 fun() @Button 16 on third joystick.
---@field Joystick8Button0 fun() @Button 0 on eighth joystick.
---@field F12 fun() @F12 function key.
---@field Mouse5 fun() @Additional (or sixth) mouse button.
---@field Joystick5Button8 fun() @Button 8 on fifth joystick.
---@field Mouse3 fun() @Additional (fourth) mouse button.
---@field JoystickButton13 fun() @Button 13 on any joystick.
---@field JoystickButton18 fun() @Button 18 on any joystick.
---@field Joystick7Button7 fun() @Button 7 on seventh joystick.
---@field Joystick2Button4 fun() @Button 4 on second joystick.
---@field Joystick7Button15 fun() @Button 15 on seventh joystick.
---@field Joystick3Button10 fun() @Button 10 on third joystick.
---@field F10 fun() @F10 function key.
---@field Joystick6Button6 fun() @Button 6 on sixth joystick.
---@field Joystick7Button0 fun() @Button 0 on seventh joystick.
---@field F8 fun() @F8 function key.
---@field Ampersand fun() @Ampersand key '&amp;'.
---@field Joystick5Button19 fun() @Button 19 on fifth joystick.
---@field Joystick1Button12 fun() @Button 12 on first joystick.
---@field Keypad1 fun() @Numeric keypad 1.
---@field Joystick2Button3 fun() @Button 3 on second joystick.
---@field RightCommand fun() @Right Command key.
---@field Pause fun() @Pause on PC machines.
---@field Joystick6Button0 fun() @Button 0 on sixth joystick.
---@field Joystick8Button16 fun() @Button 16 on eighth joystick.
---@field Joystick6Button11 fun() @Button 11 on sixth joystick.
---@field Joystick8Button18 fun() @Button 18 on eighth joystick.
---@field Joystick7Button19 fun() @Button 19 on seventh joystick.
---@field JoystickButton0 fun() @Button 0 on any joystick.
---@field Joystick6Button10 fun() @Button 10 on sixth joystick.
---@field F9 fun() @F9 function key.
---@field Joystick3Button6 fun() @Button 6 on third joystick.
---@field Space fun() @Space key.
---@field JoystickButton12 fun() @Button 12 on any joystick.
---@field Joystick4Button7 fun() @Button 7 on forth joystick.
---@field Joystick8Button13 fun() @Button 13 on eighth joystick.
---@field Joystick6Button8 fun() @Button 8 on sixth joystick.
---@field Plus fun() @Plus key '+'.
---@field Joystick6Button19 fun() @Button 19 on sixth joystick.
---@field KeypadMultiply fun() @Numeric keypad '*'.
---@field JoystickButton9 fun() @Button 9 on any joystick.
---@field JoystickButton19 fun() @Button 19 on any joystick.
---@field Joystick2Button9 fun() @Button 9 on second joystick.
---@field DoubleQuote fun() @Double quote key ''.
---@field Delete fun() @The forward delete key.
---@field F11 fun() @F11 function key.
---@field None fun() @Not assigned (never returned as the result of a keystroke).
---@field Joystick6Button5 fun() @Button 5 on sixth joystick.
---@field Joystick3Button18 fun() @Button 18 on third joystick.
---@field Joystick1Button17 fun() @Button 17 on first joystick.
---@field RightWindows fun() @Right Windows key.
---@field Joystick2Button16 fun() @Button 16 on second joystick.
---@field Joystick7Button4 fun() @Button 4 on seventh joystick.
---@field Keypad9 fun() @Numeric keypad 9.
---@field DownArrow fun() @Down arrow key.
---@field Joystick1Button9 fun() @Button 9 on first joystick.
---@field Joystick1Button16 fun() @Button 16 on first joystick.
---@field Joystick7Button13 fun() @Button 13 on seventh joystick.
---@field Joystick4Button0 fun() @Button 0 on forth joystick.
---@field Dollar fun() @Dollar sign key '$'.
---@field Joystick4Button17 fun() @Button 17 on forth joystick.
---@field BackQuote fun() @Back quote key '`'.
---@field Joystick1Button5 fun() @Button 5 on first joystick.
---@field CapsLock fun() @Capslock key.
---@field F5 fun() @F5 function key.
---@field Joystick6Button16 fun() @Button 16 on sixth joystick.
---@field Joystick7Button11 fun() @Button 11 on seventh joystick.
---@field Joystick3Button4 fun() @Button 4 on third joystick.
---@field JoystickButton16 fun() @Button 16 on any joystick.
---@field Joystick5Button9 fun() @Button 9 on fifth joystick.
---@field Joystick8Button1 fun() @Button 1 on eighth joystick.
---@field Mouse6 fun() @Additional (or seventh) mouse button.
---@field Joystick5Button14 fun() @Button 14 on fifth joystick.
---@field LeftBracket fun() @Left square bracket key '['.
---@field JoystickButton15 fun() @Button 15 on any joystick.
---@field Joystick4Button9 fun() @Button 9 on forth joystick.
---@field Joystick1Button0 fun() @Button 0 on first joystick.
---@field Caret fun() @Caret key '^'.
---@field KeypadDivide fun() @Numeric keypad '/'.
---@field Mouse2 fun() @Middle mouse button (or third button).
---@field Numlock fun() @Numlock key.
---@field LeftParen fun() @Left Parenthesis key '('.
---@field Joystick7Button3 fun() @Button 3 on seventh joystick.
---@field Joystick4Button3 fun() @Button 3 on forth joystick.
---@field Joystick3Button15 fun() @Button 15 on third joystick.
---@field Alpha4 fun() @The '4' key on the top of the alphanumeric keyboard.
---@field RightBracket fun() @Right square bracket key ']'.
---@field Backslash fun() @Backslash key ''.
---@field Joystick6Button17 fun() @Button 17 on sixth joystick.
---@field Joystick8Button8 fun() @Button 8 on eighth joystick.
---@field Joystick3Button19 fun() @Button 19 on third joystick.
---@field Joystick8Button6 fun() @Button 6 on eighth joystick.
---@field Joystick6Button9 fun() @Button 9 on sixth joystick.
---@field Joystick2Button2 fun() @Button 2 on second joystick.
---@field PageUp fun() @Page up.
---@field X fun() @'x' key.
---@field Z fun() @'z' key.
---@field Alpha5 fun() @The '5' key on the top of the alphanumeric keyboard.
---@field Joystick1Button4 fun() @Button 4 on first joystick.
---@field Joystick3Button8 fun() @Button 8 on third joystick.
---@field Joystick4Button4 fun() @Button 4 on forth joystick.
---@field Alpha8 fun() @The '8' key on the top of the alphanumeric keyboard.
---@field Joystick7Button5 fun() @Button 5 on seventh joystick.
---@field Escape fun() @Escape key.
---@field JoystickButton8 fun() @Button 8 on any joystick.
---@field Joystick8Button4 fun() @Button 4 on eighth joystick.
---@field Joystick2Button5 fun() @Button 5 on second joystick.
---@field Joystick6Button13 fun() @Button 13 on sixth joystick.
---@field Less fun() @Less than '&lt;' key.
---@field Joystick3Button13 fun() @Button 13 on third joystick.
---@field Y fun() @'y' key.
---@field W fun() @'w' key.
---@field V fun() @'v' key.
---@field UpArrow fun() @Up arrow key.
---@field Underscore fun() @Underscore '_' key.
---@field U fun() @'u' key.
---@field Joystick1Button11 fun() @Button 11 on first joystick.
---@field Joystick1Button6 fun() @Button 6 on first joystick.
---@field A fun() @'a' key.
---@field Joystick1Button13 fun() @Button 13 on first joystick.
---@field Joystick3Button3 fun() @Button 3 on third joystick.
---@field B fun() @'b' key.
---@field E fun() @'e' key.
---@field D fun() @'d' key.
---@field G fun() @'g' key.
---@field F fun() @'f' key.
---@field Joystick2Button13 fun() @Button 13 on second joystick.
---@field H fun() @'h' key.
---@field K fun() @'k' key.
---@field J fun() @'j' key.
---@field M fun() @'m' key.
---@field Joystick4Button13 fun() @Button 13 on forth joystick.
---@field O fun() @'o' key.
---@field N fun() @'n' key.
---@field Q fun() @'q' key.
---@field P fun() @'p' key.
---@field Joystick1Button18 fun() @Button 18 on first joystick.
---@field R fun() @'r' key.
---@field Break fun() @Break key.
---@field T fun() @'t' key.
---@field Backspace fun() @The backspace key.
---@field Keypad5 fun() @Numeric keypad 5.
---@field Slash fun() @Slash '/' key.
---@field Comma fun() @Comma ',' key.
---@field Semicolon fun() @Semicolon ';' key.
---@field ScrollLock fun() @Scroll lock key.
---@field JoystickButton14 fun() @Button 14 on any joystick.
---@field S fun() @'s' key.
---@field RightShift fun() @Right shift key.
---@field RightParen fun() @Right Parenthesis key ')'.
---@field RightCurlyBracket fun() @Right curly bracket key '}'.
---@field Joystick1Button14 fun() @Button 14 on first joystick.
---@field Joystick6Button7 fun() @Button 7 on sixth joystick.
---@field Joystick2Button0 fun() @Button 0 on second joystick.
---@field Greater fun() @Greater than '&gt;' key.
---@field RightArrow fun() @Right arrow key.
---@field At fun() @At key '@'.
---@field RightApple fun() @Right Command key.
---@field RightAlt fun() @Right Alt key.
---@field Question fun() @Question mark '?' key.
---@field Joystick4Button2 fun() @Button 2 on forth joystick.
---@field Print fun() @Print key.
---@field Pipe fun() @Pipe '|' key.
---@field KeypadEquals fun() @Numeric keypad '='.
---@field Period fun() @Period '.' key.
---@field Mouse0 fun() @The Left (or primary) mouse button.
---@field Joystick2Button15 fun() @Button 15 on second joystick.
---@field Joystick3Button11 fun() @Button 11 on third joystick.
---@field Percent fun() @Percent '%' key.
---@field Joystick8Button17 fun() @Button 17 on eighth joystick.
---@field LeftCurlyBracket fun() @Left curly bracket key '{'.
---@field Mouse4 fun() @Additional (fifth) mouse button.
---@field Mouse1 fun() @Right mouse button (or secondary mouse button).
---@field Joystick2Button19 fun() @Button 19 on second joystick.
---@field Joystick5Button13 fun() @Button 13 on fifth joystick.
---@field Minus fun() @Minus '-' key.
---@field Clear fun() @The Clear key.
---@field Menu fun() @Menu key.
---@field LeftWindows fun() @Left Windows key.
---@field Alpha2 fun() @The '2' key on the top of the alphanumeric keyboard.
---@field Joystick7Button6 fun() @Button 6 on seventh joystick.
---@field LeftMeta fun() @Maps to left Windows key or left Command key if physical keys are enabled in Input Manager settings, otherwise maps to left Command key only.
---@field Joystick5Button16 fun() @Button 16 on fifth joystick.
---@field LeftControl fun() @Left Control key.
---@field LeftCommand fun() @Left Command key.
---@field LeftArrow fun() @Left arrow key.
---@field LeftApple fun() @Left Command key.
---@field Joystick2Button6 fun() @Button 6 on second joystick.
---@field LeftAlt fun() @Left Alt key.
---@field Equals fun() @Equals '=' key.
---@field Joystick7Button9 fun() @Button 9 on seventh joystick.
---@field Joystick6Button15 fun() @Button 15 on sixth joystick.
---@field Joystick5Button4 fun() @Button 4 on fifth joystick.
---@field L fun() @'l' key.
---@field KeypadPlus fun() @Numeric keypad '+'.
---@field JoystickButton17 fun() @Button 17 on any joystick.
---@field JoystickButton6 fun() @Button 6 on any joystick.
---@field Joystick5Button17 fun() @Button 17 on fifth joystick.
---@field Joystick4Button18 fun() @Button 18 on forth joystick.
---@field KeypadMinus fun() @Numeric keypad '-'.
---@field Joystick5Button7 fun() @Button 7 on fifth joystick.
---@field F14 fun() @F14 function key.
---@field Keypad3 fun() @Numeric keypad 3.
---@field F3 fun() @F3 function key.
---@field Joystick1Button3 fun() @Button 3 on first joystick.
---@field Joystick6Button14 fun() @Button 14 on sixth joystick.
---@field KeypadEnter fun() @Numeric keypad Enter.
---@field Joystick2Button8 fun() @Button 8 on second joystick.
---@field KeypadPeriod fun() @Numeric keypad '.'.
---@field Joystick7Button8 fun() @Button 8 on seventh joystick.
---@field Joystick4Button16 fun() @Button 16 on forth joystick.
---@field Joystick8Button14 fun() @Button 14 on eighth joystick.
---@field Joystick2Button14 fun() @Button 14 on second joystick.
---@field Keypad7 fun() @Numeric keypad 7.
---@field Keypad4 fun() @Numeric keypad 4.
---@field Keypad2 fun() @Numeric keypad 2.
---@field Joystick8Button10 fun() @Button 10 on eighth joystick.
---@field Joystick4Button5 fun() @Button 5 on forth joystick.
---@field Alpha7 fun() @The '7' key on the top of the alphanumeric keyboard.
---@field Joystick2Button11 fun() @Button 11 on second joystick.
---@field Joystick2Button18 fun() @Button 18 on second joystick.
---@field JoystickButton7 fun() @Button 7 on any joystick.
---@field Alpha9 fun() @The '9' key on the top of the alphanumeric keyboard.
---@field Joystick4Button11 fun() @Button 11 on forth joystick.
---@field Joystick1Button2 fun() @Button 2 on first joystick.
---@field LeftShift fun() @Left shift key.
---@field JoystickButton5 fun() @Button 5 on any joystick.
---@field JoystickButton3 fun() @Button 3 on any joystick.
---@field Joystick3Button14 fun() @Button 14 on third joystick.
---@field Joystick8Button3 fun() @Button 3 on eighth joystick.
---@field Asterisk fun() @Asterisk key '*'.
---@field JoystickButton11 fun() @Button 11 on any joystick.
---@field Joystick3Button7 fun() @Button 7 on third joystick.
---@field Joystick3Button12 fun() @Button 12 on third joystick.
---@field F2 fun() @F2 function key.
---@field Exclaim fun() @Exclamation mark key '!'.
---@field Joystick2Button1 fun() @Button 1 on second joystick.
---@field JoystickButton10 fun() @Button 10 on any joystick.
---@field Joystick1Button19 fun() @Button 19 on first joystick.
---@field Joystick8Button9 fun() @Button 9 on eighth joystick.
---@field Joystick8Button7 fun() @Button 7 on eighth joystick.
---@field Joystick8Button15 fun() @Button 15 on eighth joystick.
---@field Colon fun() @Colon ':' key.
---@field Tilde fun() @Tilde '~' key.
---@field Joystick8Button5 fun() @Button 5 on eighth joystick.
---@field Joystick3Button5 fun() @Button 5 on third joystick.
---@field Joystick6Button12 fun() @Button 12 on sixth joystick.
---@field Joystick2Button10 fun() @Button 10 on second joystick.
---@field Joystick8Button11 fun() @Button 11 on eighth joystick.
---@field C fun() @'c' key.
---@field I fun() @'i' key.
---@field Joystick5Button10 fun() @Button 10 on fifth joystick.
---@field F1 fun() @F1 function key.
---@field Joystick3Button2 fun() @Button 2 on third joystick.
---@field Joystick4Button8 fun() @Button 8 on forth joystick.
---@field Joystick6Button1 fun() @Button 1 on sixth joystick.
---@field Joystick7Button17 fun() @Button 17 on seventh joystick.
---@field RightControl fun() @Right Control key.
---@field Joystick5Button11 fun() @Button 11 on fifth joystick.
---@field Joystick4Button14 fun() @Button 14 on forth joystick.
---@field Joystick6Button4 fun() @Button 4 on sixth joystick.
---@field Joystick5Button1 fun() @Button 1 on fifth joystick.
---@field Alpha1 fun() @The '1' key on the top of the alphanumeric keyboard.
---@field Joystick7Button12 fun() @Button 12 on seventh joystick.
---@field AltGr fun() @Alt Gr key.
---@field Joystick5Button6 fun() @Button 6 on fifth joystick.
---@field Joystick3Button1 fun() @Button 1 on third joystick.
---@field Alpha6 fun() @The '6' key on the top of the alphanumeric keyboard.
---@field Joystick5Button0 fun() @Button 0 on fifth joystick.
---@field End fun() @End key.
