---@class LensFlare @Script interface for a Lens flare component.
---@field brightness fun() @The strength of the flare.
---@field color fun() @The color of the flare.
---@field fadeSpeed fun() @The fade speed of the flare.
---@field flare fun() @The flare asset to use.
