---@class LightmapSettings @Stores lightmaps of the Scene.
---@field lightmapsMode fun() @NonDirectional or CombinedDirectional Specular lightmaps rendering mode.
---@field lightProbes fun() @Baked Light Probe data.
---@field lightmaps fun() @Lightmap array.
