---@class LightShape @Describes the shape of a spot light.
---@field Pyramid fun() @The shape of the spotlight resembles a pyramid or frustum. You can use this to simulate a screening or barn door effect on a normal spotlight.
---@field Cone fun() @The shape of the spot light resembles a cone. This is the default shape for spot lights.
---@field Box fun() @The shape of the spot light resembles a box oriented along the ray direction.
