---@class LightProbeProxyVolume.DataFormat @The texture data format used by the Light Probe Proxy Volume 3D texture.
---@field Float fun() @A 32-bit floating-point format is used for the Light Probe Proxy Volume 3D texture.
---@field HalfFloat fun() @A 16-bit half floating-point format is used for the Light Probe Proxy Volume 3D texture.
