---@class Lightmapping.GIWorkflowMode @Workflow mode for lightmap baking. Default is Iterative.
---@field Iterative fun() @This property is now obsolete. Use LightingSettings.autoGenerate.
---@field OnDemand fun() @This property is now obsolete. Use LightingSettings.autoGenerate.
---@field Legacy fun() @Deprecated 4.x lightmapping support.
