---@class LightType @The type of a Light.
---@field Rectangle fun() @The light is a rectangle shaped area light. It affects only baked lightmaps and lightprobes.
---@field Directional fun() @The light is a directional light.
---@field Disc fun() @The light is a disc shaped area light. It affects only baked lightmaps and lightprobes.
---@field Point fun() @The light is a point light.
---@field Spot fun() @The light is a spot light.
