---@class LightEditor @The class used to render the Light Editor when a Light is selected in the Unity Editor.
---@field OnDestroy fun() @See ScriptableObject.OnDestroy.
---@field OnSceneGUI fun() @See Editor.OnSceneGUI.
---@field Settings LightEditor.Settings @Contains all drawable elements of the LightEditor.
---@field OnEnable fun() @See ScriptableObject.OnEnable.
---@field settings fun() @The settings helper that can be used for rendering a custom LightEditor.
---@field OnInspectorGUI fun() @See Editor.OnInspectorGUI.
