---@class LightmapEditorSettings.DenoiserType @This enum is now obsolete. Use LightingSettings.DenoiserType.
---@field None fun() @This type is now obsolete. Use LightingSettings.DenoiserType.
---@field OpenImage fun() @This type is now obsolete. Use LightingSettings.DenoiserType.
---@field RadeonPro fun() @This type is now obsolete. Use LightingSettings.DenoiserType.
---@field Optix fun() @This type is now obsolete. Use LightingSettings.DenoiserType.
