---@class LocalizationGroup @This provides an auto dispose Localization system. This can be called recursively.
---@field Dispose fun() @Dispose current state.
---@field ctor fun() @Default constructor.
---@field locGroupName fun() @A current group name for the localization.
