---@class LowLevel @nil
---@field PlayerLoop LowLevel.PlayerLoop @The class representing the player loop in Unity.
---@field PlayerLoopSystem LowLevel.PlayerLoopSystem @The representation of a single system being updated by the player loop in Unity.
