---@class MenuCommand @Used to extract the context for a MenuItem.
---@field userData fun() @An integer for passing custom information to a menu item.
---@field context fun() @Context is the object that is the target of a menu command.
---@field ctor fun() @Creates a new MenuCommand object.
