---@class MeshFilter @A class to access the Mesh of the mesh filter.
---@field mesh fun() @Returns the instantiated Mesh assigned to the mesh filter.
---@field sharedMesh fun() @Returns the shared mesh of the mesh filter.
