---@class ModelImporterAnimationType @Animation mode for ModelImporter.
---@field None fun() @Generate no animation data.
---@field Human fun() @Generate a human animator.
---@field Generic fun() @Generate a generic animator.
---@field Legacy fun() @Generate a legacy animation type.
