---@class ModelImporterMaterialSearch @Material search options for ModelImporter.
---@field Everywhere fun() @Search in all project.
---@field Local fun() @Search in local Materials folder.
---@field RecursiveUp fun() @Recursive-up search in Materials folders.
