---@class ModelImporterSkinWeights @Skin weights options for ModelImporter.
---@field Custom fun() @Import a custom number of bones per vertex.
---@field Standard fun() @Import the standard number of bones per vertex (currently 4).
