---@class ModifiableMassProperties @Mass-related modifiable properties of a contact pair.
---@field inverseInertiaScale fun() @The inverse inertia scaling that the solver should apply to the first body of this contact pair.
---@field otherInverseMassScale fun() @The inverse mass scaling that the solver should apply to the second body of this contact pair.
---@field otherInverseInertiaScale fun() @The inverse inertia scaling that the solver should apply to the second body of this contact pair.
---@field inverseMassScale fun() @The inverse mass scaling that the solver should apply to the first body of this contact pair.
