---@class MPE.ChannelClientInfo @A structure that contains all of a ChannelClient's connection data.
---@field clientId fun() @The channel's channel ID (see ChannelClient.clientId).
---@field connectionId fun() @The ChannelClient's connection ID.
---@field name fun() @The ChannelClient's name (see ChannelClient.channelName. This matches the route of the URL connecting to the ChannelService. For example, 127.0.0.1:9292/&lt;channelName&gt;.
