---@class Networking.PlayerConnection.PlayerConnectionGUIUtility @Miscellaneous helper methods for Networking.PlayerConnection.PlayerConnectionGUI.
---@field GetConnectionState fun() @This method generates a state tracking object for establishing and displaying an Editor to Player Connection.
