---@class Networking.Types.HostPriority @An Enum representing the priority of a client in a match, starting at 0 and increasing.
---@field Invalid fun() @The Invalid case for a HostPriority. An Invalid host priority is not a valid host.
