---@class Networking.PlayerConnection.MessageEventArgs @Arguments passed to Action callbacks registered in PlayerConnection.
---@field data fun() @Data that is received.
---@field playerId fun() @The Player ID that the data is received from.
