---@class Networking.UnityWebRequestTexture @Helpers for downloading image files into Textures using UnityWebRequest.
---@field GetTexture fun() @Create a UnityWebRequest intended to download an image via HTTP GET and create a Texture based on the retrieved data.
