---@class Networking.UnityWebRequestAssetBundle @Helpers for downloading asset bundles using UnityWebRequest.
---@field GetAssetBundle fun() @Creates a UnityWebRequest optimized for downloading a Unity Asset Bundle via HTTP GET.
