---@class Networking.DownloadHandlerScript @An abstract base class for user-created scripting-driven DownloadHandler implementations.
---@field ctor fun() @Create a DownloadHandlerScript which allocates new buffers when passing data to callbacks.
