---@class Networking.MultipartFormDataSection @A helper object for form sections containing generic, non-file data.
---@field sectionData fun() @Returns the raw binary data contained in this section. Will not return null or a zero-length array.
---@field contentType fun() @Returns the value to use in this section's Content-Type header.
---@field sectionName fun() @Returns the name of this section, if any.
---@field fileName fun() @Returns a string denoting the desired filename of this section on the destination server.
---@field ctor fun() @Raw data section, unnamed and no Content-Type header.
