---@class Networking.Match @nil
---@field MatchInfo Networking.Match.MatchInfo @Details about a UNET MatchMaker match.
---@field MatchInfoSnapshot Networking.Match.MatchInfoSnapshot @A class describing the match information as a snapshot at the time the request was processed on the MatchMaker.
---@field NetworkMatch Networking.Match.NetworkMatch @A component for communicating with the Unity Multiplayer Matchmaking service.
