---@class Networking.ConnectionSimulatorConfig @Create configuration for network simulator; You can use this class in editor and developer build only.
---@field ctor fun() @Will create object describing network simulation parameters.
---@field Dispose fun() @Destructor.
