---@class NVIDIA.GraphicsDeviceFeature @Lists every feature ID the NVIDIA.GraphicsDevice API supports. For now, this only includes Deep Learning Super Sampling (DLSS). To check if the device supports a feature, call NVIDIA.GraphicsDevice.IsFeatureAvailable.
---@field DLSS fun() @Represents the Deep Learning Super Sampling (DLSS) feature.
