---@class NVIDIA.DLSSContext @Represents the state of DLSS.
---@field initData fun() @The immutable initialization data the DLSSContext requires.
---@field executeData fun() @The mutable state of the current DLSS object.
