---@class NVIDIA.NVUnityPlugin @Provides methods to manage loading and unloading NVIDIA module plugins.
---@field Load fun() @Attempts to dynamically load the plugin NVUnityPlugin.
---@field IsLoaded fun() @Checks wether the native plugin NVUnityPlugin in the NVIDIA native module has been loaded or not.
