---@class Overlays.IMGUIOverlay @IMGUIOverlay is an implementation of Overlay that provides a UIElements.IMGUIContainer.
---@field OnGUI fun() @Implement IMGUI controls and logic in this method.
---@field CreatePanelContent fun() @CreatePanelContent is invoked by the OverlayCanvas when this Overlay is shown.
