---@class PackageManager.Requests.Request_1 @Tracks the state of an asynchronous Unity Package Manager (Upm) server operation that returns a non-empty response.
---@field Result fun() @The response to the request.
