---@class ParticleSystemRenderSpace @How particles are aligned when rendered.
---@field Velocity fun() @Particles are aligned to their direction of travel.
---@field World fun() @Particles align with the world.
---@field Facing fun() @Particles face the eye position.
---@field Local fun() @Particles align with their local transform.
---@field View fun() @Particles face the camera plane.
