---@class PivotRotation @How is the tool handle oriented.
---@field Global fun() @The tool handle is aligned along the global axes.
---@field Local fun() @The tool handle is oriented from the active object.
