---@class Playables.INotification @The base interface for all notifications sent through the playable system.
---@field id fun() @The identifier is a name that identifies this notifications, or class of notifications.
