---@class PlayerSettings.PS4 @Player Settings for the PlayStation®4.
---@field PS4AppCategory PlayerSettings.PS4.PS4AppCategory @PS4 application category.
---@field PS4EnterButtonAssignment PlayerSettings.PS4.PS4EnterButtonAssignment @PS4 enter button assignment.
---@field PS4RemotePlayKeyAssignment PlayerSettings.PS4.PS4RemotePlayKeyAssignment @Remote Play key assignment.
