---@class PlayerSettings.tvOS @tvOS specific player settings.
---@field sdkVersion fun() @Active tvOS SDK version used for build.
---@field buildNumber fun() @The build number of the bundle
---@field requireExtendedGameController fun() @Application requires extended game controller.
---@field targetOSVersionString fun() @Deployment minimal version of tvOS.
---@field targetOSVersion fun() @Deployment minimal version of tvOS.
