---@class PlayerLoop @nil
---@field Update PlayerLoop.Update @Update phase in the native player loop.
---@field Initialization PlayerLoop.Initialization @Update phase in the native player loop.
---@field TimeUpdate PlayerLoop.TimeUpdate @Update phase in the native player loop that waits for the operating system (OS) to flip the back buffer to the display and update the time in the engine.
---@field PostLateUpdate PlayerLoop.PostLateUpdate @Update phase in the native player loop.
---@field PreUpdate PlayerLoop.PreUpdate @Update phase in the native player loop.
---@field PreLateUpdate PlayerLoop.PreLateUpdate @Update phase in the native player loop.
---@field FixedUpdate PlayerLoop.FixedUpdate @Update phase in the native player loop.
---@field EarlyUpdate PlayerLoop.EarlyUpdate @Update phase in the native player loop.
