---@class Playables.INotificationReceiver @Implement this interface to create a class that will receives notifications from PlayableOutput.
---@field OnNotify fun() @The method called when a notification is raised.
