---@class PointerType @Pointer types.
---@field Pen fun() @The pointer type for pen events.
---@field Mouse fun() @The pointer type for mouse events.
---@field Touch fun() @The pointer type for touch events.
