---@class PrimitiveType @The various primitives that can be created using the GameObject.CreatePrimitive function.
---@field Cylinder fun() @A cylinder primitive.
---@field Capsule fun() @A capsule primitive.
---@field Cube fun() @A cube primitive.
---@field Quad fun() @A quad primitive.
---@field Plane fun() @A plane primitive.
---@field Sphere fun() @A sphere primitive.
