---@class ProceduralProcessorUsage @Deprecated feature, no longer available
---@field All fun() @Deprecated feature, no longer available
---@field Half fun() @Deprecated feature, no longer available
---@field Unsupported fun() @Deprecated feature, no longer available
---@field One fun() @Deprecated feature, no longer available
