---@class Profiling.FrameDataView.MethodInfo @Managed method descriptor structure.
---@field methodName fun() @Fully qualified method name.
---@field sourceFileLine fun() @Line number in the source file where the method is defined.
---@field sourceFileName fun() @Name of a source file where the method is defined.
