---@class Progress.TimeDisplayMode @Specifies what kind of time information the progress indicator displays.
---@field ShowRemainingTime fun() @The progress indicator displays the time remaining.
---@field NoTimeShown fun() @The progress indicator does not display any time information.
---@field ShowRunningTime fun() @The progress indicator displays the running time.
