---@class RectTransform.Edge @Enum used to specify one edge of a rectangle.
---@field Top fun() @The top edge.
---@field Right fun() @The right edge.
---@field Bottom fun() @The bottom edge.
---@field Left fun() @The left edge.
