---@class ReflectionProbe.ReflectionProbeEvent @Types of events that occur when ReflectionProbe components are used in a Scene.
---@field ReflectionProbeAdded fun() @An event that occurs when a Reflection Probe component is added to a Scene or enabled in a Scene.
---@field ReflectionProbeRemoved fun() @An event that occurs when a Reflection Probe component is unloaded from a Scene or disabled in a Scene.
