---@class Rendering.ShaderQuality @Shader quality preset.
---@field Low fun() @Low quality shader preset.
---@field High fun() @High quality shader preset.
---@field Medium fun() @Medium quality shader preset.
