---@class Rendering.BuiltinShaderDefine @Defines set by editor when compiling shaders, based on the target platform and GraphicsTier.
---@field UNITY_HARDWARE_TIER3 fun() @UNITY_HARDWARE_TIER3 is set when compiling shaders for GraphicsTier.Tier3.
---@field UNITY_VIRTUAL_TEXTURING fun() @Is virtual texturing enabled and supported on this platform.
---@field UNITY_LIGHTMAP_RGBM_ENCODING fun() @UNITY_LIGHTMAP_RGBM_ENCODING is set when lightmap textures are using RGBM encoding to store the values in the texture.
---@field UNITY_METAL_SHADOWS_USE_POINT_FILTERING fun() @UNITY_METAL_SHADOWS_USE_POINT_FILTERING is set if shadow sampler should use point filtering on iOS Metal.
---@field SHADER_API_MOBILE fun() @SHADER_API_MOBILE is set when compiling shader for mobile platforms.
---@field UNITY_HARDWARE_TIER2 fun() @UNITY_HARDWARE_TIER2 is set when compiling shaders for GraphicsTier.Tier2.
---@field UNITY_ENABLE_REFLECTION_BUFFERS fun() @UNITY_ENABLE_REFLECTION_BUFFERS is set when deferred shading renders reflection probes in deferred mode. With this option set reflections are rendered into a per-pixel buffer. This is similar to the way lights are rendered into a per-pixel buffer. UNITY_ENABLE_REFLECTION_BUFFERS is on by default when using deferred shading, but you can turn it off by setting “No support” for the Deferred Reflections shader option in Graphics Settings. When the setting is off, reflection probes are rendered per-object, similar to the way forward rendering works.
---@field SHADER_API_GLES30 fun() @SHADER_API_ES30 is set when the Graphics API is OpenGL ES 3 and the minimum supported OpenGL ES 3 version is OpenGL ES 3.0.
---@field UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS fun() @UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS is set automatically for platforms that don't require full floating-point precision support in fragment shaders.
---@field UNITY_SPECCUBE_BOX_PROJECTION fun() @UNITY_SPECCUBE_BLENDING is set if Reflection Probes Box Projection is enabled.
---@field UNITY_UNIFIED_SHADER_PRECISION_MODEL fun() @Unity sets UNITY_UNIFIED_SHADER_PRECISION_MODEL if, in Player Settings, you set Shader Precision Model to Unified.
---@field UNITY_ENABLE_DETAIL_NORMALMAP fun() @UNITY_ENABLE_DETAIL_NORMALMAP is set if Detail Normal Map should be sampled if assigned.
---@field SHADER_API_DESKTOP fun() @SHADER_API_DESKTOP is set when compiling shader for desktop platforms.
---@field UNITY_SPECCUBE_BLENDING fun() @UNITY_SPECCUBE_BLENDING is set if Reflection Probes Blending is enabled.
---@field UNITY_ASTC_NORMALMAP_ENCODING fun() @Unity enables UNITY_ASTC_NORMALMAP_ENCODING when DXT5nm-style normal maps are used on Android, iOS or tvOS.
---@field UNITY_PBS_USE_BRDF1 fun() @UNITY_PBS_USE_BRDF1 is set if Standard Shader BRDF1 should be used.
---@field UNITY_NO_RGBM fun() @UNITY_NO_RGBM is set when compiling shader for platform that do not support RGBM, so dLDR will be used instead.
---@field UNITY_FRAMEBUFFER_FETCH_AVAILABLE fun() @UNITY_FRAMEBUFFER_FETCH_AVAILABLE is set when compiling shaders for platforms where framebuffer fetch is potentially available.
---@field UNITY_PBS_USE_BRDF3 fun() @UNITY_PBS_USE_BRDF3 is set if Standard Shader BRDF3 should be used.
---@field UNITY_PBS_USE_BRDF2 fun() @UNITY_PBS_USE_BRDF2 is set if Standard Shader BRDF2 should be used.
---@field UNITY_NO_SCREENSPACE_SHADOWS fun() @UNITY_NO_SCREENSPACE_SHADOWS is set when screenspace cascaded shadow maps are disabled.
---@field UNITY_NO_FULL_STANDARD_SHADER fun() @UNITY_NO_FULL_STANDARD_SHADER is set if Standard shader BRDF3 with extra simplifications should be used.
---@field UNITY_LIGHTMAP_FULL_HDR fun() @UNITY_LIGHTMAP_FULL_HDR is set when lightmap textures are not using any encoding to store the values in the texture.
---@field UNITY_HARDWARE_TIER1 fun() @UNITY_HARDWARE_TIER1 is set when compiling shaders for GraphicsTier.Tier1.
---@field UNITY_NO_DXT5nm fun() @UNITY_NO_DXT5nm is set when compiling shader for platform that do not support DXT5NM, meaning that normal maps will be encoded in RGB instead.
---@field UNITY_LIGHTMAP_DLDR_ENCODING fun() @UNITY_LIGHTMAP_DLDR_ENCODING is set when lightmap textures are using double LDR encoding to store the values in the texture.
---@field UNITY_ENABLE_NATIVE_SHADOW_LOOKUPS fun() @UNITY_ENABLE_NATIVE_SHADOW_LOOKUPS enables use of built-in shadow comparison samplers on OpenGL ES 2.0.
---@field UNITY_COLORSPACE_GAMMA fun() @UNITY_COLORSPACE_GAMMA is set when compiling shaders for Gamma Color Space.
---@field UNITY_LIGHT_PROBE_PROXY_VOLUME fun() @UNITY_LIGHT_PROBE_PROXY_VOLUME is set when Light Probe Proxy Volume feature is supported by the current graphics API and is enabled in the Graphics Tier settings. You can only set a Graphics Tier in the Built-in Render Pipeline.
---@field UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS fun() @UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS is set when Semitransparent Shadows are enabled.
---@field UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION fun() @Unity enables UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION when Vulkan pre-transform is enabled and supported on the target build platform.
