---@class Rendering.CameraProperties @Camera related properties in CullingParameters.
---@field SetShadowCullingPlane fun() @Set a shadow culling plane.
---@field GetCameraCullingPlane fun() @Get a camera culling plane.
---@field SetCameraCullingPlane fun() @Set a camera culling plane.
---@field GetShadowCullingPlane fun() @Get a shadow culling plane.
