---@class Rendering.RendererUtils.RendererList @Represents a subset of visible GameObjects.
---@field nullRendererList fun() @Returns an empty RendererList.
---@field isValid fun() @Indicates whether the RendererList is valid or not. If the RendererList is valid, this returns true. Otherwise, this returns false.
