---@class Rendering.SortingLayerRange @Describes a renderer's sorting layer range.
---@field all fun() @A range that includes all objects.
---@field upperBound fun() @Inclusive upper bound for the range.
---@field ctor fun() @Sets the inclusive range for a sorting layer object.
---@field lowerBound fun() @Inclusive lower bound for the range.
