---@class Rendering.ColorWriteMask @Specifies which color components will get written into the target framebuffer.
---@field Alpha fun() @Write alpha component.
---@field Blue fun() @Write blue component.
---@field Red fun() @Write red component.
---@field All fun() @Write all components (R, G, B and Alpha).
---@field Green fun() @Write green component.
