---@class Rendering.AlbedoSwatchInfo @Contains the custom albedo swatch data.
---@field name fun() @Name of the albedo swatch to show in the physically based renderer validator user interface.
---@field color fun() @Color of the albedo swatch that is shown in the physically based rendering validator user interface.
---@field minLuminance fun() @The minimum luminance value used to validate the albedo for the physically based rendering albedo validator.
---@field maxLuminance fun() @The maximum luminance value used to validate the albedo for the physically based rendering albedo validator.
