---@class Rendering.CameraLateLatchMatrixType @The types of camera matrices that support late latching.
---@field ViewProjection fun() @The camera's view projection matrix.
---@field InverseView fun() @The camera's inverse view matrix.
---@field View fun() @The camera's view matrix.
---@field InverseViewProjection fun() @The camera's inverse view projection matrix.
