---@class Rendering.VirtualTexturing.GPUCacheSetting @Settings for a virtual texturing GPU cache.
---@field sizeInMegaBytes fun() @Size in MegaBytes of the cache created with these settings.
---@field format fun() @Format of the cache these settings are applied to.
