---@class Rendering.ScopedRenderPass @Represents an active render pass until disposed.
---@field Dispose fun() @Ends the current render pass in the ScriptableRenderContext that was used to create the ScopedRenderPass.
