---@class Rendering.ReflectionProbeUsage @Reflection Probe usage.
---@field BlendProbes fun() @Reflection probes are enabled. Blending occurs only between probes, useful in indoor environments. The renderer will use default reflection if there are no reflection probes nearby, but no blending between default reflection and probe will occur.
---@field BlendProbesAndSkybox fun() @Reflection probes are enabled. Blending occurs between probes or probes and default reflection, useful for outdoor environments.
---@field Simple fun() @Reflection probes are enabled, but no blending will occur between probes when there are two overlapping volumes.
---@field Off fun() @Reflection probes are disabled, skybox will be used for reflection.
