---@class Rendering.ReflectionProbeMode @Reflection probe's update mode.
---@field Custom fun() @Reflection probe uses a custom texture specified by the user.
---@field Baked fun() @Reflection probe is baked in the Editor.
---@field Realtime fun() @Reflection probe is updating in real-time.
