---@class Rendering.VirtualTexturing.Procedural.CPUTextureStack @Procedural virtual texturing stack where request data resides in CPU memory.
---@field ctor fun() @Create a new CPUTextureStack object.
