---@class Rendering.ScopedSubPass @Represents an active sub pass until disposed.
---@field Dispose fun() @Ends the current sub pass in the ScriptableRenderContext that was used to create the ScopedSubPass.
