---@class Rendering.LightShadowResolution @Shadow resolution options for a Light.
---@field Medium fun() @Medium shadow map resolution.
---@field Low fun() @Low shadow map resolution.
---@field High fun() @High shadow map resolution.
---@field VeryHigh fun() @Very high shadow map resolution.
---@field FromQualitySettings fun() @Use resolution from QualitySettings (default).
