---@class Rendering.VirtualTexturing.FilterMode @Filtering modes available in the virtual texturing system.
---@field Bilinear fun() @Bilinear filtering.
---@field Trilinear fun() @Trilinear filtering.
