---@class Rendering.TextureDimension @Texture dimension (type).
---@field CubeArray fun() @Cubemap array texture (CubemapArray).
---@field Tex2D fun() @2D texture (Texture2D).
---@field Unknown fun() @Texture type is not initialized or unknown.
---@field Tex3D fun() @3D volume texture (Texture3D).
---@field None fun() @No texture is assigned.
---@field Cube fun() @Cubemap texture.
---@field Any fun() @Any texture type.
---@field Tex2DArray fun() @2D array texture (Texture2DArray).
