---@class Rendering.GlobalKeyword @Represents a global shader keyword.
---@field name fun() @The name of the shader keyword. (Read Only)
---@field Create fun() @Creates and returns a Rendering.GlobalKeyword that represents a new or existing global shader keyword.
---@field ctor fun() @Creates and returns a GlobalKeyword struct that represents an existing global shader keyword.
