---@class ReplacePrefabOptions @Flags for the PrefabUtility.ReplacePrefab function.
---@field ReplaceNameBased fun() @Replaces the Prefab using name based lookup in the transform hierarchy.
---@field ConnectToPrefab fun() @Connects the passed objects to the Prefab after uploading the Prefab.
---@field Default fun() @Replaces Prefabs by matching pre-existing connections to the Prefab.
