---@class ResolutionDialogSetting @Resolution dialog setting.
---@field HiddenByDefault fun() @Hide the resolution dialog on first launch.
---@field Enabled fun() @Show the resolution dialog on first launch.
---@field Disabled fun() @Never show the resolution dialog.
