---@class RigidbodyConstraints @Use these flags to constrain motion of Rigidbodies.
---@field FreezePositionY fun() @Freeze motion along the Y-axis.
---@field None fun() @No constraints.
---@field FreezeRotationX fun() @Freeze rotation along the X-axis.
---@field FreezeRotationY fun() @Freeze rotation along the Y-axis.
---@field FreezePositionZ fun() @Freeze motion along the Z-axis.
---@field FreezeRotation fun() @Freeze rotation along all axes.
---@field FreezeAll fun() @Freeze rotation and motion along all axes.
---@field FreezeRotationZ fun() @Freeze rotation along the Z-axis.
---@field FreezePositionX fun() @Freeze motion along the X-axis.
---@field FreezePosition fun() @Freeze motion along all axes.
