---@class RigidbodyInterpolation @Rigidbody interpolation mode.
---@field None fun() @No Interpolation.
---@field Interpolate fun() @Interpolation will always lag a little bit behind but can be smoother than extrapolation.
---@field Extrapolate fun() @Extrapolation will predict the position of the rigidbody based on the current velocity.
