---@class RuntimeAnimatorController @The runtime representation of the AnimatorController. Use this representation to change the Animator Controller during runtime.
---@field animationClips fun() @Retrieves all AnimationClip used by the controller.
