---@class ScreenOrientation @Describes screen orientation.
---@field Portrait fun() @Portrait orientation.
---@field AutoRotation fun() @Auto-rotates the screen as necessary toward any of the enabled orientations.
---@field LandscapeRight fun() @Landscape orientation, clockwise from the portrait orientation.
---@field LandscapeLeft fun() @Landscape orientation, counter-clockwise from the portrait orientation.
---@field PortraitUpsideDown fun() @Portrait orientation, upside down.
