---@class Scripting.GarbageCollector.Mode @Garbage collector operation mode.
---@field Manual fun() @Disable automatic invokations of the garbage collector, but allow manually invokations.
---@field Enabled fun() @Enable garbage collector.
---@field Disabled fun() @Disable garbage collector.
