---@class ScriptingRuntimeVersion @Available scripting runtimes to be used by the Editor and Players.
---@field Legacy fun() @Use the stable version of the scripting runtime.
---@field Latest fun() @Use the most recent version of the scripting runtime available.
