---@class SearchService.ISearchEngine_1 @The base interface for search engines that implement a search operation.
---@field Search fun() @This function returns an IEnumerable of items that satisfy the search query.
