---@class Search.DisplayMode @Options for setting the display mode to use for a search view.
---@field None fun() @Unspecified ISearchView display mode.
---@field List fun() @Display as a list view.
---@field Grid fun() @Display as a grid of icons of various sizes.
---@field Table fun() @Display search results in a table.
