---@class Search.Providers @nil
---@field SceneQueryEngineParameterTransformerAttribute fun() @Attribute class that defines a custom parameter transformer function applied for a query running in a scene provider defined by a scene custom filter using Search.Providers.SceneQueryEngineFilterAttribute.
---@field SceneQueryEngineFilterAttribute Search.Providers.SceneQueryEngineFilterAttribute @Custom attribute is used to customize the search engine used by the scene search provider.
