---@class Search.ParseResult_1 @A ParseResult represents the result of a parsing operation.
---@field parsedValue fun() @The parsing result.
---@field success fun() @Flag indicating if the parsing succeeded or not.
---@field ctor fun() @Create a ParseResult.
---@field none fun() @Default value when no ParsetResult is available.
