---@class Search.Providers.SceneQueryEngineFilterAttribute @Custom attribute is used to customize the search engine used by the scene search provider.
---@field ctor fun() @Create a filter with the corresponding token and supported operators.
