---@class Search.QueryEngine @A QueryEngine defines how to build a query from an input string.It can be customized to support custom filters and operators.Default query engine of type object.
---@field ctor fun() @Construct a new QueryEngine.
