---@class Security @Webplayer security related class. Not supported from 5.4.0 onwards.
---@field LoadAndVerifyAssembly fun() @Loads an assembly and checks that it is allowed to be used in the webplayer. (Web Player is no Longer Supported).
---@field PrefetchSocketPolicy fun() @Prefetch the webplayer socket security policy from a non-default port number.
