---@class SerializedPropertyType @Type of a SerializedProperty.
---@field FixedBufferSize fun() @Fixed buffer size property.
---@field BoundsInt fun() @Bounds with Integer values property.
---@field Enum fun() @Enumeration property.
---@field Integer fun() @Integer property, for example int, byte, short, uint and long.
---@field Vector4 fun() @4D vector property.
---@field Vector3Int fun() @3D integer vector property.
---@field Quaternion fun() @Quaternion property.
---@field Boolean fun() @Boolean property.
---@field Vector2Int fun() @2D integer vector property.
---@field Rect fun() @Rectangle property.
---@field ManagedReference fun() @Property that references an object that does not derive from UnityEngine.Object.
---@field Character fun() @Character property.
---@field ObjectReference fun() @Reference to an object that derives from UnityEngine.Object.
---@field Vector2 fun() @2D vector property.
---@field RectInt fun() @Rectangle with Integer values property.
---@field Vector3 fun() @3D vector property.
---@field String fun() @String property.
---@field Gradient fun() @Gradient property.
---@field ArraySize fun() @Array size property.
---@field Color fun() @Color property.
---@field AnimationCurve fun() @AnimationCurve property.
---@field Bounds fun() @Bounds property.
---@field LayerMask fun() @LayerMask property.
---@field Hash128 fun() @A Hash128 property.
---@field Float fun() @Float or Double property.
---@field ExposedReference fun() @A reference to another Object in the Scene.
