---@class ShadowResolution @Default shadow resolution.
---@field Low fun() @Low shadow map resolution.
---@field High fun() @High shadow map resolution.
---@field VeryHigh fun() @Very high shadow map resolution.
---@field Medium fun() @Medium shadow map resolution.
