---@class ShadowProjection @Shadow projection type for Quality Settings.
---@field CloseFit fun() @Close fit shadow maps with linear fadeout.
---@field StableFit fun() @Stable shadow maps with spherical fadeout.
