---@class ShadowObjectsFilter @The filters that Unity can use when it renders GameObjects in the shadow pass.
---@field AllObjects fun() @Renders all GameObjects.
---@field StaticOnly fun() @Only renders GameObjects that include the Static Shadow Caster tag.
---@field DynamicOnly fun() @Only renders GameObjects that do not include the Static Shadow Caster tag.
