---@class ShortcutManagement.ShortcutArguments @Provides data for shortcut action methods invoked by the shortcut system.
---@field context fun() @Instance of the context in which the shortcut was triggered.
---@field stage fun() @The stage at which a shortcut action was invoked.
