---@class SocialPlatforms.Range @The score range a leaderboard query should include.
---@field ctor fun() @Constructor for a score range, the range starts from a specific value and contains a maxium score count.
---@field count fun() @The total amount of scores retreived.
---@field from fun() @The rank of the first score which is returned.
