---@class SortingLayer @SortingLayer allows you to set the render order of multiple sprites easily. There is always a default SortingLayer named Default which all sprites are added to initially. Added more SortingLayers to easily control the order of rendering of groups of sprites. Layers can be ordered before or after the default layer.
---@field GetLayerValueFromName fun() @Returns the final sorting layer value. See Also: GetLayerValueFromID.
---@field layers fun() @Returns all the layers defined in this project.
---@field IDToName fun() @Returns the unique id of the layer. Will return &lt;unknown layer&gt; if an invalid id is given.
---@field GetLayerValueFromID fun() @Returns the final sorting layer value. To determine the sorting order between the various sorting layers, use this method to retrieve the final sorting value and use CompareTo to determine the order.
---@field id fun() @This is the unique id assigned to the layer. It is not an ordered running value and it should not be used to compare with other layers to determine the sorting order.
---@field NameToID fun() @Returns the id given the name. Will return 0 if an invalid name was given.
---@field value fun() @This is the relative value that indicates the sort order of this layer relative to the other layers.
---@field IsValid fun() @Returns true if the id provided is a valid layer id.
---@field name fun() @Returns the name of the layer as defined in the TagManager.
