---@class Sprites @nil
---@field AtlasSettings Sprites.AtlasSettings @Describes the final atlas texture.
---@field PackerJob Sprites.PackerJob @Current Sprite Packer job definition.
---@field SpriteUtility Sprites.SpriteUtility @Helper utilities for accessing Sprite data.
---@field IPackerPolicy Sprites.IPackerPolicy @Sprite packing policy interface. Provide a custom implementation to control which Sprites go into which atlases.
---@field DataUtility Sprites.DataUtility @Helper utilities for accessing Sprite data.
---@field Packer Sprites.Packer @Sprite Packer helpers.
