---@class SpriteTileMode @Tiling mode for SpriteRenderer.tileMode.
---@field Adaptive fun() @Sprite Renderer tiles the sprite once the Sprite Renderer size is above SpriteRenderer.adaptiveModeThreshold.
---@field Continuous fun() @Sprite Renderer tiles the sprite continuously when is set to SpriteRenderer.tileMode.
