---@class SpriteSortPoint @Determines the position of the Sprite used for sorting the Renderer.
---@field Pivot fun() @The pivot of the Sprite is used as the point for sorting the Renderer.
---@field Center fun() @The center of the Sprite is used as the point for sorting the Renderer.
