---@class StereoTargetEyeMask @Enum values for the Camera's targetEye property.
---@field None fun() @Do not render either eye to the HMD.
---@field Both fun() @Render both eyes to the HMD.
---@field Right fun() @Render only the right eye to the HMD.
---@field Left fun() @Render only the Left eye to the HMD.
