---@class TerrainExtensions @Extension methods to the Terrain class, used only for the UpdateGIMaterials method used by the Global Illumination System.
---@field UpdateGIMaterials fun() @Schedules an update of the albedo and emissive Textures of a system that contains the Terrain.
