---@class TestTools.CoveredMethodStats @Describes the summary of the code coverage for the specified method used by TestTools.Coverage. For an example of typical usage, see TestTools.Coverage.GetStatsFor.
---@field method fun() @The covered method.
---@field uncoveredSequencePoints fun() @The total number of uncovered sequence points in the method.
---@field totalSequencePoints fun() @The total number of sequence points in the method.
