---@class TextureImporterShape @The shape of the imported texture.
---@field TextureCube fun() @Import the texture as a Cubemap.
---@field Texture2DArray fun() @Import the texture as a 2D Array texture.
---@field Texture3D fun() @Import the texture as a 3D texture.
---@field Texture2D fun() @Import the texture as a 2D texture (default).
