---@class Tilemaps.Tilemap.Orientation @Determines the orientation of Tiles in the Tilemap.
---@field XZ fun() @Orients Tiles in the XZ plane.
---@field YZ fun() @Orients Tiles in the YZ plane.
---@field XY fun() @Orients Tiles in the XY plane.
---@field Custom fun() @Use a custom orientation to all tiles in the tile map.
---@field ZY fun() @Orients Tiles in the ZY plane.
---@field ZX fun() @Orients Tiles in the ZX plane.
---@field YX fun() @Orients Tiles in the YX plane.
