---@class Toolbars @nil
---@field EditorToolbarDropdown Toolbars.EditorToolbarDropdown @A clickable dropdown used with EditorToolbarElementAttribute.
---@field EditorToolbarElementAttribute Toolbars.EditorToolbarElementAttribute @The EditorToolbarElement attribute allows you to make available a specific VisualElement for use in an Editor Toolbar.
---@field EditorToolbarButton Toolbars.EditorToolbarButton @A clickable button used with EditorToolbarElementAttribute.
---@field EditorToolbarToggle Toolbars.EditorToolbarToggle @A toggle used with EditorToolbarElementAttribute.
---@field IAccessContainerWindow Toolbars.IAccessContainerWindow @Implement this interface to gain access to toolbar's container EditorWindow.
---@field EditorToolbarUtility Toolbars.EditorToolbarUtility @Editor utility functions when working with EditorToolbar.
