---@class Tree @Tree Component for the tree creator.
---@field data fun() @Data asociated to the Tree.
---@field hasSpeedTreeWind fun() @Tells if there is wind data exported from SpeedTree are saved on this component.
