---@class tvOS.DeviceGeneration @iOS device generation.
---@field AppleTV1Gen fun() @Apple TV HD.
---@field AppleTVHD fun() @Apple TV HD.
---@field AppleTV4K fun() @First generation Apple TV 4K.
---@field AppleTV2Gen fun() @First generation Apple TV 4K.
---@field AppleTV4K2Gen fun() @Second generation Apple TV 4K.
