---@class TypeCache.TypeCollection.Enumerator @Enumerates the elements of a TypeCollection.
---@field MoveNext fun() @Advances the enumerator to the next element of the collection.
---@field Current fun() @Gets the element at the current position of the enumerator.
---@field Dispose fun() @Releases all resources used by the Enumerator.
