---@class TypeCache.MethodCollection @Represents a read-only collection of MethodInfo and implements an IList interface.
---@field IndexOf fun() @Gets the first occurrence of an item in the MethodCollection.
---@field IsReadOnly fun() @Whether the MethodCollection is read-only. This property is always set to true.
---@field CopyTo fun() @Copies the collection to an array.
---@field Index_operator fun() @Gets the element at the specified index.
---@field Enumerator TypeCache.MethodCollection.Enumerator @Enumerates the elements of a MethodCollection.
---@field GetEnumerator fun() @Gets an enumerator that iterates through a MethodCollection.
---@field IsSynchronized fun() @Whether the MethodCollection is synchronized. This property is always set to true.
---@field Contains fun() @Determines whether an element is in the MethodCollection.
---@field Count fun() @The number of elements in MethodCollection.
---@field IsFixedSize fun() @Whether the MethodCollection is of a fixed size. This property is always set to true.
