---@class U2D.SpriteRendererDataAccessExtensions @A list of methods that allow the caller to override what the SpriteRenderer renders.
---@field DeactivateDeformableBuffer fun() @Stop using the deformable buffer to render the Sprite and use the original mesh instead.
