---@class U2D.SpriteShapeUtility @A static class that helps tessellate a SpriteShape mesh.
---@field Generate fun() @Generate a mesh based on input parameters.
---@field GenerateSpriteShape fun() @Generate a mesh based on input parameters.
