---@class UIElements.Experimental.ITransitionAnimations @Provides helper methods to create transition animations  for VisualElement style values
---@field Size fun() @Triggers an animation changing this element's size style values.
---@field Layout fun() @Triggers an animation changing this element's layout style values.
---@field Position fun() @Triggers an animation changing this element's transform position.
---@field Start fun() @Starts a transition animation on this VisualElement.
---@field Rotation fun() @Triggers an animation changing this element's transform rotation.
---@field TopLeft fun() @Triggers an animation changing this element's positioning style values.
---@field Scale fun() @Triggers an animation changing this element's transform scale.
