---@class UIElements.VisualElementFocusChangeDirection @Define focus change directions for the VisualElementFocusRing.
---@field lastValue fun() @Last value for the direction defined by this class.
---@field right fun() @The focus is moving to the right.
---@field left fun() @The focus is moving to the left.
