---@class UIElements.Align @Defines the alignement behavior along an axis.
---@field Center fun() @Items are centered on the axis.
---@field FlexEnd fun() @End margin of the item is placed at the end of the axis.
---@field Auto fun() @Let Flex decide.
---@field FlexStart fun() @Start margin of the item is placed at the start of the axis.
---@field Stretch fun() @Default. stretch to fill the axis while respecting min/max values.
