---@class UIElements.Hash128Field @Makes a field for editing an Hash128.
---@field labelUssClassName fun() @USS class name of labels in elements of this type.
---@field ctor fun() @Initializes and returns an instance of Hash128Field.
---@field ussClassName fun() @USS class name of elements of this type.
---@field inputUssClassName fun() @USS class name of input elements in elements of this type.
---@field UxmlFactory fun() @Instantiates a Hash128Field using the data read from a UXML file.
---@field UxmlTraits fun() @Defines UxmlTraits for the Hash128Field.
