---@class UIElements.PopupWindow @Styled visual element that matches the EditorGUILayout.Popup IMGUI element.
---@field ctor fun() @Initializes and returns an instance of PopupWindow.
---@field ussClassName fun() @USS class name of elements of this type.
---@field contentUssClassName fun() @USS class name of content elements in elements of this type.
---@field UxmlFactory fun() @Instantiates a PopupWindow using the data read from a UXML file.
---@field UxmlTraits UIElements.PopupWindow.UxmlTraits @Defines UxmlTraits for the PopupWindow.
