---@class UIElements.ICustomStyle @This interface exposes methods to read custom style properties applied from USS files to visual elements.
---@field TryGetValue fun() @Gets the value associated with the specified CustomStyleProperty_1.
