---@class UIElements.TransformOriginOffset @Specifies the alignment keywords for TransformOrigin.
---@field Center fun() @The origin of the transform operation is set to the center of the element.
---@field Bottom fun() @The origin of the transform operation set to the bottom of the element.
---@field Top fun() @The origin of the transform operation is set to the top of the element.
---@field Right fun() @The origin of the transform operation is set to the right of the element.
---@field Left fun() @The origin of the transform operation is is set to the left of the element.
