---@class UIElements.StyleKeyword @Keyword that can be used on any style value types.
---@field Initial fun() @The initial (or default) value of a style property.
---@field Undefined fun() @Means that there's no keyword defined for that property.
---@field None fun() @For style properties accepting none.
---@field Auto fun() @For style properties accepting auto.
---@field Null fun() @Means that an inline style from IStyle has no value or keyword.
