---@class UIElements.PopupWindow.UxmlTraits @Defines UxmlTraits for the PopupWindow.
---@field uxmlChildElementsDescription fun() @Returns an empty enumerable, as popup windows generally do not have children.
