---@class UIElements.MouseButton @Describes a MouseButton.
---@field MiddleMouse fun() @The Middle Mouse Button.
---@field RightMouse fun() @The Right Mouse Button.
---@field LeftMouse fun() @The Left Mouse Button.
