---@class UIElements.IFocusEvent @Interface for focus events.
---@field direction fun() @Direction of the focus change.
---@field relatedTarget fun() @Related target. See implementation for specific meaning.
