---@class UIElements.TextElement.UxmlTraits @Defines UxmlTraits for the TextElement.
---@field Init fun() @Initializer for the UxmlTraits for the TextElement.
---@field uxmlChildElementsDescription fun() @Enumerator to get the child elements of the UxmlTraits of TextElement.
