---@class UIElements.Toggle @A Toggle is a clickable element that represents a boolean value.
---@field labelUssClassName fun() @USS class name for Labels in Toggle elements.
---@field ctor fun() @Creates a Toggle with no label.
---@field ussClassName fun() @USS class name for Toggle elements.
---@field checkmarkUssClassName fun() @USS class name of Images in Toggle elements.
---@field noTextVariantUssClassName fun() @USS class name of Toggle elements that have no text.
---@field UxmlTraits UIElements.Toggle.UxmlTraits @Defines UxmlTraits for the Toggle.
---@field UxmlFactory fun() @Instantiates a Toggle using data from a UXML file.
---@field inputUssClassName fun() @USS class name of input elements in Toggle elements.
---@field textUssClassName fun() @USS class name of Text elements in Toggle elements.
