---@class UIElements.Overflow @Defines what should happend if content overflows an element bounds.
---@field Visible fun() @The overflow is not clipped. It renders outside the element's box. Default Value.
---@field Hidden fun() @The overflow is clipped, and the rest of the content will be invisible.
