---@class UIElements.Scroller.UxmlTraits @Defines UxmlTraits for the Scroller.
---@field Init fun() @Initialize Scroller properties using values from the attribute bag.
---@field uxmlChildElementsDescription fun() @Returns an empty enumerable, as scrollers do not have children.
