---@class UIElements.Vector2IntField @A Vector2Int editor field.
---@field labelUssClassName fun() @USS class name of labels in elements of this type.
---@field ctor fun() @Initializes and returns an instance of Vector2IntField.
---@field ussClassName fun() @USS class name of elements of this type.
---@field inputUssClassName fun() @USS class name of input elements in elements of this type.
---@field UxmlFactory fun() @Instantiates a Vector2IntField using the data read from a UXML file.
---@field UxmlTraits UIElements.Vector2IntField.UxmlTraits @Defines UxmlTraits for the Vector2IntField.
