---@class UIElements.INotifyValueChanged_1 @Interface for controls that hold a value and can notify when it is changed by user input.
---@field SetValueWithoutNotify fun() @Sets the value and, even if different, doesn't notify registers callbacks with a ChangeEvent_1
---@field value fun() @The value the control holds.
