---@class UIElements.Scale @Reprensents the scale applied as an element's transformations. The center point that will not move when the scaling is applied is the TransformOrigin.
---@field None fun() @Returns a value of Scale without any scaling applied.
