---@class UIElements.IUxmlAttributes @This type allows UXML attribute value retrieval during the VisualElement instantiation. An instance will be provided to the factory method - see UXMLFactoryAttribute.
---@field TryGetAttributeValue fun() @Get the value of an attribute as a string.
