---@class UIElements.StylePropertyNameCollection.Enumerator @Enumerates the elements of a StylePropertyNameCollection.
---@field MoveNext fun() @Advances the enumerator to the next element of the StylePropertyNameCollection.
---@field Current fun() @Gets the element at the current position of the enumerator.
---@field Dispose fun() @Releases all resources used by the StylePropertyNameCollection enumerator.
