---@class UIElements.StyleFloat @Style value that can be either a float or a StyleKeyword.
---@field value fun() @The float value.
---@field ctor fun() @Creates from either a float or a StyleKeyword.
---@field keyword fun() @The style keyword.
