---@class UIElements.StyleTranslate @Style value that can be either a Translate or a StyleKeyword.
---@field value fun() @The Translate value.
---@field ctor fun() @Creates from either a Translate or a StyleKeyword.
---@field keyword fun() @The style keyword.
