---@class UIElements.NavigationMoveEvent.Direction @Move event direction.
---@field Right fun() @Righto.
---@field Down fun() @Downo.
---@field None fun() @No specific direction.
---@field Up fun() @Upo.
---@field Left fun() @Lefto.
