---@class UIElements.Label @Provides an Element displaying text.
---@field ussClassName fun() @USS class name of elements of this type.
---@field UxmlFactory fun() @Instantiates a Label using the data read from a UXML file.
---@field ctor fun() @Constructs a label.
---@field UxmlTraits fun() @Defines UxmlTraits for the Label.
