---@class UIElements.Box @Styled visual element to match the IMGUI Box Style.
---@field ussClassName fun() @USS class name of elements of this type.
---@field ctor fun() @Initializes and returns an instance of Box.
---@field UxmlFactory fun() @Instantiates a Box using the data read from a UXML file.
