---@class UIElements.DropdownMenuSeparator @A separator menu item.
---@field subMenuPath fun() @The submenu path where the separator will be added. Path components are delimited by forward slashes ('/').
---@field ctor fun() @Constructor.
