---@class UIElements.PointerLeaveEvent @This event is sent when a pointer exits an element and all of its descendants.
---@field ctor fun() @Constructor. Avoid creating new event instances. Instead, use GetPooled() to get an instance from a pool of reusable event instances.
---@field Init fun() @Resets the event members to their initial values.
