---@class UIElements.MouseCaptureController @Class that manages capturing mouse events.
---@field CaptureMouse fun() @Assigns an event handler to capture mouse events.
---@field IsMouseCaptured fun() @Checks if there is a handler capturing the mouse.
---@field HasMouseCapture fun() @Checks if the event handler is capturing the mouse.
---@field ReleaseMouse fun() @Stops an event handler from capturing the mouse.
