---@class UIElements.UxmlRootElementFactory @Factory for the root UXML element.
---@field uxmlQualifiedName fun() @Returns the qualified name for this element.
---@field uxmlName fun() @Returns UXML.
---@field Create fun() @Returns null.
---@field substituteForTypeQualifiedName fun() @Returns the empty string, as the root element can not appear anywhere else bit at the root of the document.
---@field substituteForTypeName fun() @Returns the empty string, as the root element can not appear anywhere else bit at the root of the document.
---@field substituteForTypeNamespace fun() @Returns the empty string, as the root element can not appear anywhere else bit at the root of the document.
