---@class UIElements.RectField @A Rect editor field.
---@field labelUssClassName fun() @USS class name of labels in elements of this type.
---@field ctor fun() @Initializes and returns an instance of RectField.
---@field ussClassName fun() @USS class name of elements of this type.
---@field inputUssClassName fun() @USS class name of input elements in elements of this type.
---@field UxmlFactory fun() @Instantiates a RectField using the data read from a UXML file.
---@field UxmlTraits UIElements.RectField.UxmlTraits @Defines UxmlTraits for the RectField.
