---@class UIElements.ListViewReorderMode @Options to change the drag and drop mode for items in the ListView.
---@field Animated fun() @ListView will add drag handles before every item, that can be used to drag a single item with animated visual feedback.
---@field Simple fun() @ListView will display the standard blue line dragger on reorder.
