---@class UIElements.ITransitionEvent @Interface for all transition events.
---@field stylePropertyNames fun() @The names of the properties associated with the transition.
---@field elapsedTime fun() @The number of seconds the transition has been running, excluding delay phase time.
