---@class UIElements.TextField @A textfield is a rectangular area where the user can edit a string.
---@field multiline fun() @Set this to true to allow multiple lines in the textfield and false if otherwise.
---@field inputUssClassName fun() @USS class name of input elements in elements of this type.
---@field ctor fun() @Creates a new textfield.
---@field ussClassName fun() @USS class name of elements of this type.
---@field UxmlFactory fun() @Instantiates a TextField using the data read from a UXML file.
---@field UxmlTraits UIElements.TextField.UxmlTraits @Defines UxmlTraits for the TextField.
---@field value fun() @The string currently being exposed by the field.
---@field labelUssClassName fun() @USS class name of labels in elements of this type.
---@field SelectRange fun() @Selects text in the textfield between cursorIndex and selectionIndex.
