---@class UIElements.IStyle @This interface provides access to a VisualElement inline style data.
---@field maxWidth fun() @Maximum width for an element, when it is flexible or measures its own size.
---@field borderLeftColor fun() @Color of the element's left border.
---@field borderBottomRightRadius fun() @The radius of the bottom-right corner when a rounded rectangle is drawn in the element's box.
---@field rotate fun() @A rotation transformation.
---@field transformOrigin fun() @The transformation origin is the point around which a transformation is applied.
---@field paddingLeft fun() @Space reserved for the left edge of the padding during the layout phase.
---@field paddingRight fun() @Space reserved for the right edge of the padding during the layout phase.
---@field transitionTimingFunction fun() @Determines how intermediate values are calculated for properties modified by a transition effect.
---@field flexGrow fun() @Specifies how the item will shrink relative to the rest of the flexible items inside the same container.
---@field wordSpacing fun() @Increases or decreases the space between words.
---@field top fun() @Top distance from the element's box during layout.
---@field textShadow fun() @Drop shadow of the text.
---@field overflow fun() @How a container behaves if its content overflows its own box.
---@field borderTopWidth fun() @Space reserved for the top edge of the border during the layout phase.
---@field borderTopColor fun() @Color of the element's top border.
---@field paddingBottom fun() @Space reserved for the bottom edge of the padding during the layout phase.
---@field right fun() @Right distance from the element's box during layout.
---@field marginLeft fun() @Space reserved for the left edge of the margin during the layout phase.
---@field justifyContent fun() @Justification of children on the main axis of this container.
---@field flexBasis fun() @Initial main size of a flex item, on the main flex axis. The final layout might be smaller or larger, according to the flex shrinking and growing determined by the other flex properties.
---@field alignContent fun() @Alignment of the whole area of children on the cross axis if they span over multiple lines in this container.
---@field bottom fun() @Bottom distance from the element's box during layout.
---@field flexDirection fun() @Direction of the main axis to layout children in a container.
---@field letterSpacing fun() @Increases or decreases the space between characters.
---@field unityFontStyleAndWeight fun() @Font style and weight (normal, bold, italic) to draw the element's text.
---@field color fun() @Color to use when drawing the text of an element.
---@field borderTopLeftRadius fun() @The radius of the top-left corner when a rounded rectangle is drawn in the element's box.
---@field display fun() @Defines how an element is displayed in the layout.
---@field minWidth fun() @Minimum width for an element, when it is flexible or measures its own size.
---@field marginTop fun() @Space reserved for the top edge of the margin during the layout phase.
---@field textOverflow fun() @The element's text overflow mode.
---@field unityBackgroundScaleMode fun() @Background image scaling in the element's box.
---@field unityOverflowClipBox fun() @Specifies which box the element content is clipped against.
---@field flexShrink fun() @Specifies how the item will shrink relative to the rest of the flexible items inside the same container.
---@field height fun() @Fixed height of an element for the layout.
---@field borderBottomColor fun() @Color of the element's bottom border.
---@field unitySliceRight fun() @Size of the 9-slice's right edge when painting an element's background image.
---@field alignSelf fun() @Similar to align-items, but only for this specific element.
---@field unitySliceLeft fun() @Size of the 9-slice's left edge when painting an element's background image.
---@field flexWrap fun() @Placement of children over multiple lines if not enough space is available in this container.
---@field alignItems fun() @Alignment of children on the cross axis of this container.
---@field unitySliceTop fun() @Size of the 9-slice's top edge when painting an element's background image.
---@field unityTextOutlineColor fun() @Outline color of the text.
---@field unityTextOverflowPosition fun() @The element's text overflow position.
---@field borderBottomLeftRadius fun() @The radius of the bottom-left corner when a rounded rectangle is drawn in the element's box.
---@field visibility fun() @Specifies whether or not an element is visible.
---@field whiteSpace fun() @Word wrapping over multiple lines if not enough space is available to draw the text of an element.
---@field borderTopRightRadius fun() @The radius of the top-right corner when a rounded rectangle is drawn in the element's box.
---@field unityTextOutlineWidth fun() @Outline width of the text.
---@field unityTextAlign fun() @Horizontal and vertical text alignment in the element's box.
---@field marginBottom fun() @Space reserved for the bottom edge of the margin during the layout phase.
---@field width fun() @Fixed width of an element for the layout.
---@field borderRightWidth fun() @Space reserved for the right edge of the border during the layout phase.
---@field minHeight fun() @Minimum height for an element, when it is flexible or measures its own size.
---@field unitySliceBottom fun() @Size of the 9-slice's bottom edge when painting an element's background image.
---@field unityParagraphSpacing fun() @Increases or decreases the space between paragraphs.
---@field unityFontDefinition fun() @Font to draw the element's text.
---@field unityFont fun() @Font to draw the element's text.
---@field maxHeight fun() @Maximum height for an element, when it is flexible or measures its own size.
---@field unityBackgroundImageTintColor fun() @Tinting color for the element's backgroundImage.
---@field translate fun() @A translate transformation.
---@field borderRightColor fun() @Color of the element's right border.
---@field transitionProperty fun() @Properties to which a transition effect should be applied.
---@field paddingTop fun() @Space reserved for the top edge of the padding during the layout phase.
---@field backgroundColor fun() @Background color to paint in the element's box.
---@field borderBottomWidth fun() @Space reserved for the bottom edge of the border during the layout phase.
---@field fontSize fun() @Font size to draw the element's text.
---@field transitionDuration fun() @Time a transition animation should take to complete.
---@field transitionDelay fun() @Duration to wait before starting a property's transition effect when its value changes.
---@field marginRight fun() @Space reserved for the right edge of the margin during the layout phase.
---@field position fun() @Element's positioning in its parent container.
---@field cursor fun() @Mouse cursor to display when the mouse pointer is over an element.
---@field opacity fun() @Specifies the transparency of an element.
---@field borderLeftWidth fun() @Space reserved for the left edge of the border during the layout phase.
---@field backgroundImage fun() @Background image to paint in the element's box.
---@field scale fun() @A scaling transformation.
---@field left fun() @Left distance from the element's box during layout.
