---@class UIElements.Wrap @By default, items will all try to fit onto one line. You can change that and allow the items to wrap as needed with this property.
---@field WrapReverse fun() @Items will wrap onto multiple lines from bottom to top.
---@field Wrap fun() @All items will be on one line. Default Value.
---@field NoWrap fun() @All items will be on one line. Default Value.
