---@class UIElements.HelpBoxMessageType @User message types.
---@field None fun() @Neutral message.
---@field Error fun() @Error message.
---@field Warning fun() @Warning message.
---@field Info fun() @Info message.
