---@class UIElements.FieldMouseDragger_1 @Provides dragging on a visual element to change a value field.
---@field ctor fun() @FieldMouseDragger's constructor.
---@field dragging fun() @Is dragging.
---@field startValue fun() @Start value before drag.
