---@class UIElements.SerializedPropertyChangeEvent @An event sent when a value in a PropertyField changes.
---@field changedProperty fun() @The SerializedProperty whose value changed.
---@field GetPooled fun() @Gets an event from the event pool and initializes it with the values provided. Use this function instead of creating new events. Events obtained using this method need to be released back to the pool. You can use Dispose() to release them.
---@field ctor fun() @Constructor. Use GetPooled instead.
---@field Init fun() @Sets the event to its initial state.
