---@class UIElements.SliderInt @A slider containing Integer discrete values.
---@field labelUssClassName fun() @USS class name of labels in elements of this type.
---@field ctor fun() @Constructors for the SliderInt.
---@field pageSize fun() @The value to add or remove to the SliderInt.value when it is clicked.
---@field ussClassName fun() @USS class name of elements of this type.
---@field inputUssClassName fun() @USS class name of input elements in elements of this type.
---@field UxmlFactory fun() @Instantiates a SliderInt using the data read from a UXML file.
---@field UxmlTraits UIElements.SliderInt.UxmlTraits @Defines UxmlTraits for the SliderInt.
