---@class UIElements.InspectorElement @Create a VisualElement inspector from a SerializedObject.
---@field debugVariantUssClassName fun() @USS class name of elements of this type, when they are displayed in debug USS mode.
---@field iMGUIContainerUssClassName fun() @USS class name of IMGUI containers in elements of this type.
---@field ctor fun() @InspectorElement constructor.
---@field FillDefaultInspector fun() @Adds default inspector property fields under a container VisualElement
---@field ussClassName fun() @USS class name of elements of this type.
---@field iMGUICustomVariantUssClassName fun() @USS class name of elements of this type, when they are displayed in IMGUI custom mode.
---@field UxmlFactory fun() @Instantiates a InspectorElement using the data read from a UXML file.
---@field UxmlTraits UIElements.InspectorElement.UxmlTraits @Defines UxmlTraits for the InspectorElement.
---@field uIEInspectorVariantUssClassName fun() @USS class name of elements of this type, when they are displayed in UIElements inspector mode.
---@field uIECustomVariantUssClassName fun() @USS class name of elements of this type, when they are displayed in UIElements custom mode.
---@field debugInternalVariantUssClassName fun() @USS class name of elements of this type, when they are displayed in debug internal mode.
---@field iMGUIInspectorVariantUssClassName fun() @USS class name of elements of this type, when they are displayed in IMGUI inspector mode.
---@field uIEDefaultVariantUssClassName fun() @USS class name of elements of this type, when they are displayed in UIElements default mode.
---@field noInspectorFoundVariantUssClassName fun() @USS class name of elements of this type, when no inspector is found.
---@field iMGUIDefaultVariantUssClassName fun() @USS class name of elements of this type, when they are displayed in IMGUI default mode.
---@field customInspectorUssClassName fun() @USS class name of custom inspector elements in elements of this type.
