---@class UIElements.Image @A VisualElement representing a source texture.
---@field image fun() @The texture to display in this image.
---@field sprite fun() @The sprite to display in this image.
---@field sourceRect fun() @The source rectangle inside the texture relative to the top left corner.
---@field ussClassName fun() @USS class name of elements of this type.
---@field UxmlFactory fun() @Instantiates an Image using the data read from a UXML file.
---@field UxmlTraits UIElements.Image.UxmlTraits @Defines UxmlTraits for the Image.
---@field uv fun() @The base texture coordinates of the Image relative to the bottom left corner.
---@field tintColor fun() @Tinting color for this Image.
---@field ctor fun() @Constructor.
---@field scaleMode fun() @ScaleMode used to display the Image.
---@field vectorImage fun() @The VectorImage to display in this image.
