---@class UIElements.Experimental.StyleValues @Container object used to animate multiple style values at once.
---@field top fun() @Top distance from the element's box during layout.
---@field borderTopRightRadius fun() @The radius of the top-right corner when a rounded rectangle is drawn in the element's box.
---@field borderTopWidth fun() @Space reserved for the top edge of the border during the layout phase.
---@field width fun() @Fixed width of an element for the layout.
---@field borderRightWidth fun() @Space reserved for the right edge of the border during the layout phase.
---@field borderBottomRightRadius fun() @The radius of the bottom-right corner when a rounded rectangle is drawn in the element's box.
---@field right fun() @Right distance from the element's box during layout.
---@field marginLeft fun() @Space reserved for the left edge of the margin during the layout phase.
---@field unityBackgroundImageTintColor fun() @Tinting color for the element's backgroundImage.
---@field paddingTop fun() @Space reserved for the top edge of the padding during the layout phase.
---@field opacity fun() @Specifies the transparency of an element.
---@field backgroundColor fun() @Background color to paint in the element's box.
---@field borderColor fun() @Color of the border to paint inside the element's box.
---@field height fun() @Fixed height of an element for the layout.
---@field paddingLeft fun() @Space reserved for the left edge of the padding during the layout phase.
---@field bottom fun() @Bottom distance from the element's box during layout.
---@field paddingBottom fun() @Space reserved for the bottom edge of the padding during the layout phase.
---@field borderBottomWidth fun() @Space reserved for the bottom edge of the border during the layout phase.
---@field marginRight fun() @Space reserved for the right edge of the margin during the layout phase.
---@field paddingRight fun() @Space reserved for the right edge of the padding during the layout phase.
---@field marginTop fun() @Space reserved for the top edge of the margin during the layout phase.
---@field marginBottom fun() @Space reserved for the bottom edge of the margin during the layout phase.
---@field color fun() @Color to use when drawing the text of an element.
---@field left fun() @Left distance from the element's box during layout.
---@field borderTopLeftRadius fun() @The radius of the top-left corner when a rounded rectangle is drawn in the element's box.
---@field borderLeftWidth fun() @Space reserved for the left edge of the border during the layout phase.
---@field flexShrink fun() @Specifies how the item will shrink relative to the rest of the flexible items inside the same container.
---@field flexGrow fun() @Specifies how much the item will grow relative to the rest of the flexible items inside the same container.
---@field borderBottomLeftRadius fun() @The radius of the bottom-left corner when a rounded rectangle is drawn in the element's box.
