---@class UIElements.BoundsField @A Bounds editor field.
---@field UxmlTraits UIElements.BoundsField.UxmlTraits @Defines UxmlTraits for the BoundsField.
---@field inputUssClassName fun() @USS class name of input elements in elements of this type.
---@field ctor fun() @Initializes and returns an instance of BoundsField.
---@field centerFieldUssClassName fun() @USS class name of center fields in elements of this type.
---@field ussClassName fun() @USS class name of elements of this type.
---@field labelUssClassName fun() @USS class name of labels in elements of this type.
---@field UxmlFactory fun() @Instantiates a BoundsField using the data read from a UXML file.
---@field extentsFieldUssClassName fun() @USS class name of extents fields in elements of this type.
