---@class UILineInfo @Information about a generated line of text.
---@field height fun() @Height of the line.
---@field leading fun() @Space in pixels between this line and the next line.
---@field startCharIdx fun() @Index of the first character in the line.
---@field topY fun() @The upper Y position of the line in pixels. This is used for text annotation such as the caret and selection box in the InputField.
