---@class Unity.Collections.NativeSlice_1 @Native Slice.
---@field SliceConvert fun() @SliceConvert.
---@field ctor fun() @Constructor.
---@field Index_operator fun() @Access NativeSlice elements by index. Notice that structs are returned by value and not by reference.
---@field GetEnumerator fun() @GetEnumerator.
---@field operator_NativeArrayT fun() @Implicit operator for creating a NativeSlice from a NativeArray.
---@field ToArray fun() @Convert NativeSlice to array.
---@field Stride fun() @Returns stride set for Slice.
---@field Length fun() @Number of elements in the slice.
---@field CopyFrom fun() @Copy all the elements from a NativeSlice or managed array of the same length.
---@field SliceWithStride fun() @SliceWithStride.
---@field CopyTo fun() @Copy all the elements of the slice to a NativeArray or managed array of the same length.
