---@class Unity.Profiling.LowLevel @nil
---@field ProfilerMarkerDataType Unity.Profiling.LowLevel.ProfilerMarkerDataType @Options for the Profiler metadata type.
---@field Unsafe Unity.Profiling.LowLevel.Unsafe @nil
---@field MarkerFlags Unity.Profiling.LowLevel.MarkerFlags @Profiler marker usage flags.
