---@class Unity.Profiling.Editor @nil
---@field ProfilerModuleViewController Unity.Profiling.Editor.ProfilerModuleViewController @Provides a single view of content for a ProfilerModule displayed in the Profiler window.
---@field ProfilerModuleMetadataAttribute Unity.Profiling.Editor.ProfilerModuleMetadataAttribute @Provides metadata related to a ProfilerModule, such as its name and icon path.
---@field ProfilerModuleChartType Unity.Profiling.Editor.ProfilerModuleChartType @Options for a Profiler module’s chart type.
---@field ProfilerCounterDescriptor Unity.Profiling.Editor.ProfilerCounterDescriptor @Provides a descriptor for a Profiler counter.
---@field ProfilerModule Unity.Profiling.Editor.ProfilerModule @Represents a Profiler module in the Profiler window.
