---@class Unity.Profiling.LowLevel.Unsafe @nil
---@field ProfilerUnsafeUtility Unity.Profiling.LowLevel.Unsafe.ProfilerUnsafeUtility @Utility class which provides access to low level Profiler API.
---@field ProfilerCategoryDescription Unity.Profiling.LowLevel.Unsafe.ProfilerCategoryDescription @Provides information about Profiler category.
---@field ProfilerRecorderDescription Unity.Profiling.LowLevel.Unsafe.ProfilerRecorderDescription @Gets the description of a Profiler metric.
---@field ProfilerMarkerData Unity.Profiling.LowLevel.Unsafe.ProfilerMarkerData @Describes Profiler metadata parameter that can be associated with a sample.
---@field ProfilerRecorderHandle Unity.Profiling.LowLevel.Unsafe.ProfilerRecorderHandle @Gets the handle of a Profiler metric.
