---@class Unity.Collections.Allocator @Used to specify allocation type for NativeArray.
---@field AudioKernel fun() @Allocation associated with a DSPGraph audio kernel.
---@field Persistent fun() @Persistent allocation.
---@field None fun() @No allocation.
---@field TempJob fun() @Temporary job allocation.
---@field Temp fun() @Temporary allocation.
---@field Invalid fun() @Invalid allocation.
