---@class Unity.Profiling.LowLevel.Unsafe.ProfilerUnsafeUtility.TimestampConversionRatio @Fraction that converts the Profiler timestamp to nanoseconds.
---@field Denominator fun() @Denominator of timestamp to nanoseconds conversion fraction.
---@field Numerator fun() @Numerator of timestamp to nanoseconds conversion fraction.
