---@class Unity.Profiling.LowLevel.Unsafe.ProfilerCategoryDescription @Provides information about Profiler category.
---@field Name fun() @Gets Profiler category name as string.
---@field Id fun() @Profiler category identifier.
---@field Flags fun() @Profiler category flags.
---@field Color fun() @Profiler category color.
---@field NameUtf8 fun() @Profiler category name pointer.
---@field NameUtf8Len fun() @Profiler category name length.
