---@class VersionControl.ConfigField @Describes the configuration fields of the version control that the user has selected in the Unity Editor.
---@field name fun() @Name of the configuration field.
---@field label fun() @Label that is displayed next to the configuration field in the editor.
---@field isRequired fun() @This is true if the configuration field is required for the version control plugin to function correctly.
---@field isPassword fun() @This is true if the configuration field is a password field.
---@field description fun() @Descrition of the configuration field.
