---@class VersionControl.IInspectorWindowExtension @Version control system extension that allows extending inspector.
---@field OnVersionControlBar fun() @Allows you to add custom GUI controls to the version control bar in the specified inspector.
---@field InvalidateVersionControlBarState fun() @Resets any cached state for the version control bar.
