---@class VerticalWrapMode @Wrapping modes for text that reaches the vertical boundary.
---@field Overflow fun() @Text well continue to generate when reaching vertical boundary.
---@field Truncate fun() @Text will be clipped when reaching the vertical boundary.
