---@class VFX.VFXExpressionValues @This class is a wrapper to the set of expression values.
---@field GetInt fun() @Returns an integer that corresponds to the bound named expression. IF this entry is not available, or the type doesn't match, an exception is thrown.
---@field GetUInt fun() @Returns an unsigned integer that corresponds to the bound named expression. If this entry is not available, or the type doesn't match, an exception is thrown.
---@field GetVector2 fun() @Returns a Vector2 that corresponds to the bound named expression. If this entry is not available, or the type doesn't match, an exception is thrown.
---@field GetVector4 fun() @Returns a Vector4 that corresponds to the bound named expression. If this entry is not available, or the type doesn't match, an exception is thrown.
---@field GetVector3 fun() @Returns a Vector3 that corresponds to the bound named expression. If this entry is not available, or the type doesn't match, an exception is thrown.
---@field GetAnimationCurve fun() @Returns a an animation curve that corresponds to the bound named expression. If this entry is not available, or the type doesn't match, an exception is thrown.
---@field GetTexture fun() @Returns a texture that corresponds to the bound named expression. If this entry is not available, or the type doesn't match, an exception is thrown.
---@field GetBool fun() @Returns a boolean that corresponds to the bound named expression. If this entry is not available, or the type doesn't match, an exception is thrown.
---@field GetMatrix4x4 fun() @Returns a Matrix4 that corresponds to the bound named expression. If this entry is not available, or the type doesn't match, an exception is thrown.
---@field GetGradient fun() @Returns a gradient that corresponds to the bound named expression. If this entry is not available, or the type doesn't match, an exception is thrown.
---@field GetFloat fun() @Returns a float that corresponds to the bound named expression. If this entry is not available, or the type doesn't match, an exception is thrown.
---@field GetMesh fun() @Returns a mesh that corresponds to the bound named expression. If this entry is not available, or the type doesn't match, an exception is thrown.
