---@class WaitForSeconds @Suspends the coroutine execution for the given amount of seconds using scaled time.
---@field ctor fun() @Suspends the coroutine execution for the given amount of seconds using scaled time.
