---@class WaitForSecondsRealtime @Suspends the coroutine execution for the given amount of seconds using unscaled time.
---@field ctor fun() @Creates a yield instruction to wait for a given number of seconds using unscaled time.
---@field waitTime fun() @The given amount of seconds that the yield instruction will wait for.
