---@class Windows.Crypto @Class representing cryptography algorithms.
---@field ComputeSHA1Hash fun() @Computes SHA1 hash value for the specified byte array.
---@field ComputeMD5Hash fun() @Computes MD5 hash value for the specified byte array.
