---@class Windows.WebCam.CapturePixelFormat @The encoded image or video pixel format to use for PhotoCapture and VideoCapture.
---@field PNG fun() @Portable Network Graphics Format.
---@field JPEG fun() @Encode photo in JPEG format.
---@field NV12 fun() @8-bit Y plane followed by an interleaved U/V plane with 2x2 subsampling.
---@field BGRA32 fun() @8 bits per channel (blue, green, red, and alpha).
