---@class WindZoneMode @Modes a Wind Zone can have, either Spherical or Directional.
---@field Spherical fun() @Wind zone only has an effect inside the radius, and has a falloff from the center towards the edge.
---@field Directional fun() @Wind zone affects the entire Scene in one direction.
