---@class Windows.Speech.SpeechSystemStatus @Represents the current status of the speech recognition system or a dictation recognizer.
---@field Stopped fun() @Speech recognition system is stopped.
---@field Running fun() @Speech recognition system is running.
---@field Failed fun() @Speech recognition system has encountered an error and is in an indeterminate state.
