---@class WSA.WindowActivationState @Specifies the set of reasons that a windowActivated event was raised.
---@field CodeActivated fun() @The window was activated.
---@field PointerActivated fun() @The window was activated by pointer interaction.
---@field Deactivated fun() @The window was deactivated.
