---@class WSASubtarget @Target device type for a Windows Store application to run on.
---@field HoloLens fun() @The application targets HoloLens.
---@field AnyDevice fun() @The application targets all devices that run Windows Store applications.
---@field Mobile fun() @Application targets mobile devices.
---@field PC fun() @Application targets PCs.
