---@class XcodeBuildConfig @Build configurations for the Xcode project Unity generates.
---@field Release fun() @Sets the build configuration to Release for the Xcode project Unity generates.
---@field Debug fun() @Sets the build configuration to Debug for the Xcode project Unity generates.
