---@class XR.Bone @A tracked bone on the device at an XR.XRNode in the XR input subsystem.
---@field TryGetRotation fun() @Gets the world rotation of the bone.
---@field TryGetPosition fun() @Gets the world position of the bone
---@field TryGetChildBones fun() @Get the child bones of this bone.
---@field TryGetParentBone fun() @Gets the parent of this bone.
