---@class XR.XRDisplaySubsystem.LateLatchNode @Type of node to be late latched.
---@field Head fun() @Head node type for late latching. This represents the camera node in the pose hierarchy.
---@field RightHand fun() @Right hand node type for late latching. This represents the right hand anchor node in the pose hierarchy.
---@field LeftHand fun() @Left hand node type for late latching. This represents the left hand anchor node in the pose hierarchy.
