---@class XR.XRMirrorViewBlitModeDesc @Struct that describes the mirror view blit mode.
---@field blitModeDesc fun() @String that describes the mirror view blit mode.
---@field blitMode fun() @Mirror view blit mode Id. For details, see XRMirrorViewBlitMode. In case of provider's custom blit mode, the value wouldn't be the reserved XRMirrorViewBlitMode.
